# CIC-IDS-2017 feature preparation

This notebook starts from the cleaned dataset produced by `01_data_exploration.ipynb`. Its first stage removes identifier columns that would encourage memorization of the CIC-IDS-2017 laboratory, separates the remaining features from the multiclass target, and creates a reproducible stratified train/test split. No scaling, encoding, correlation filtering, resampling or learned feature selection is performed before the split.

## 1. Imports and paths

In [1]:
from itertools import combinations
from pathlib import Path

import pandas as pd
from IPython.display import display
from sklearn.feature_selection import mutual_info_classif
from sklearn.model_selection import train_test_split

processed_dataset_candidates = [
    Path("../data/processed/cicids2017_cleaned.parquet"),
    Path("ml/data/processed/cicids2017_cleaned.parquet"),
]

PROCESSED_DATA_PATH = next(
    (
        path.resolve()
        for path in processed_dataset_candidates
        if path.exists()
    ),
    None,
)

if PROCESSED_DATA_PATH is None:
    raise FileNotFoundError(
        "Could not find cicids2017_cleaned.parquet. "
        "Run 01_data_exploration.ipynb first."
    )

RANDOM_STATE = 42
TEST_SIZE = 0.20

print(f"Processed dataset: {PROCESSED_DATA_PATH}")
print(f"File size: {PROCESSED_DATA_PATH.stat().st_size / (1024 ** 2):,.2f} MiB")
print(f"Random state: {RANDOM_STATE}")
print(f"Test fraction: {TEST_SIZE:.0%}")

Processed dataset: C:\Users\ademz\Desktop\9raya\DoS-Intrusion-Detection-System\ml\data\processed\cicids2017_cleaned.parquet
File size: 360.48 MiB
Random state: 42
Test fraction: 20%

## 2. Load and validate the cleaned data

Confirm that the processed file matches the final dimensions and target structure recorded in the exploration notebook.

In [2]:
data = pd.read_parquet(PROCESSED_DATA_PATH)

EXPECTED_ROWS = 2_824_752
EXPECTED_COLUMNS = 76
EXPECTED_LABELS = 15

dataset_validation = pd.DataFrame(
    {
        "Observed": [
            data.shape[0],
            data.shape[1],
            data["Label"].nunique(dropna=False)
            if "Label" in data.columns
            else 0,
            int(data["Label"].isna().sum())
            if "Label" in data.columns
            else data.shape[0],
        ],
        "Expected": [
            EXPECTED_ROWS,
            EXPECTED_COLUMNS,
            EXPECTED_LABELS,
            0,
        ],
    },
    index=[
        "Rows",
        "Columns",
        "Detailed target classes",
        "Missing target labels",
    ],
)
display(dataset_validation)

if not dataset_validation["Observed"].equals(
    dataset_validation["Expected"]
):
    raise AssertionError(
        "The cleaned dataset does not match the expected EDA output."
    )

print("The cleaned dataset matches the final EDA output.")

                         Observed  Expected
Rows                      2824752   2824752
Columns                        76        76
Detailed target classes        15        15
Missing target labels           0         0

The cleaned dataset matches the final EDA output.

## 3. Review all cleaned columns

Display the complete cleaned schema before excluding identifiers or separating the target.

In [3]:
cleaned_column_overview = pd.DataFrame(
    {
        "Position": range(1, len(data.columns) + 1),
        "Column": data.columns,
        "Data type": data.dtypes.astype(str).to_numpy(),
    }
).set_index("Position")

with pd.option_context("display.max_rows", None):
    display(cleaned_column_overview)
print(f"Total cleaned columns: {len(cleaned_column_overview)}")

                              Column Data type
Position
1                            Flow ID    object
2                             Src IP    object
3                           Src Port   float64
4                             Dst IP    object
5                           Dst Port   float64
6                           Protocol   float64
7                          Timestamp    object
8                      Flow Duration   float64
9                   Total Fwd Packet   float64
10                 Total Bwd packets   float64
11        Total Length of Fwd Packet   float64
12        Total Length of Bwd Packet   float64
13             Fwd Packet Length Max   float64
14             Fwd Packet Length Min   float64
15            Fwd Packet Length Mean   float64
16             Fwd Packet Length Std   float64
17             Bwd Packet Length Max   float64
18             Bwd Packet Length Min   float64
19            Bwd Packet Length Mean   float64
20             Bwd Packet Length Std   float64
21                      Flow Bytes/s   float64
22                    Flow Packets/s   float64
23                     Flow IAT Mean   float64
24                      Flow IAT Std   float64
25                      Flow IAT Max   float64
26                      Flow IAT Min   float64
27                     Fwd IAT Total   float64
28                      Fwd IAT Mean   float64
29                       Fwd IAT Std   float64
30                       Fwd IAT Max   float64
31                       Fwd IAT Min   float64
32                     Bwd IAT Total   float64
33                      Bwd IAT Mean   float64
34                       Bwd IAT Std   float64
35                       Bwd IAT Max   float64
36                       Bwd IAT Min   float64
37                     Fwd PSH Flags   float64
38                     Fwd URG Flags   float64
39                 Fwd Header Length   float64
40                 Bwd Header Length   float64
41                     Fwd Packets/s   float64
42                     Bwd Packets/s   float64
43                 Packet Length Min   float64
44                 Packet Length Max   float64
45                Packet Length Mean   float64
46                 Packet Length Std   float64
47            Packet Length Variance   float64
48                    FIN Flag Count   float64
49                    SYN Flag Count   float64
50                    RST Flag Count   float64
51                    PSH Flag Count   float64
52                    ACK Flag Count   float64
53                    URG Flag Count   float64
54                    CWR Flag Count   float64
55                    ECE Flag Count   float64
56                     Down/Up Ratio   float64
57               Average Packet Size   float64
58              Fwd Segment Size Avg   float64
59              Bwd Segment Size Avg   float64
60               Subflow Fwd Packets   float64
61                 Subflow Fwd Bytes   float64
62               Subflow Bwd Packets   float64
63                 Subflow Bwd Bytes   float64
64                FWD Init Win Bytes   float64
65                Bwd Init Win Bytes   float64
66                 Fwd Act Data Pkts   float64
67                  Fwd Seg Size Min   float64
68                       Active Mean   float64
69                        Active Std   float64
70                        Active Max   float64
71                        Active Min   float64
72                         Idle Mean   float64
73                          Idle Std   float64
74                          Idle Max   float64
75                          Idle Min   float64
76                             Label    object

Total cleaned columns: 76

## 4. Remove identifier and leakage-prone columns

`Flow ID`, endpoint IP addresses and `Timestamp` describe this particular laboratory capture rather than transferable flow behavior. These fixed schema exclusions do not depend on statistics calculated from the dataset, so remove them directly from the cleaned table before separating features and target. Ports and `Protocol` are retained for now.

In [4]:
identifier_columns = [
    "Flow ID",
    "Src IP",
    "Dst IP",
    "Timestamp",
]
missing_identifier_columns = [
    column for column in identifier_columns if column not in data.columns
]
if missing_identifier_columns:
    raise KeyError(
        "Expected identifier columns are missing: "
        f"{missing_identifier_columns}"
    )

identifier_decisions = pd.DataFrame(
    {
        "Column": identifier_columns,
        "Reason for exclusion": [
            "Constructed flow identifier; encourages record memorization",
            "Source identity is specific to the CIC-IDS-2017 laboratory",
            "Destination identity is specific to the CIC-IDS-2017 laboratory",
            "Encodes the published attack schedule and capture day",
        ],
    }
)
display(identifier_decisions)

data.drop(columns=identifier_columns, inplace=True)
print(f"Columns remaining after fixed exclusions: {data.shape[1]}")

      Column                               Reason for exclusion
0    Flow ID  Constructed flow identifier; encourages record...
1     Src IP  Source identity is specific to the CIC-IDS-201...
2     Dst IP  Destination identity is specific to the CIC-ID...
3  Timestamp  Encodes the published attack schedule and capt...

Columns remaining after fixed exclusions: 72

## 5. Separate features and target

Keep the original 15-class `Label` as the target. Using `pop` separates it without duplicating the large feature table in memory.

In [5]:
y = data.pop("Label")
X = data
del data

print(f"Feature rows: {X.shape[0]:,}")
print(f"Feature columns: {X.shape[1]}")
print(f"Target rows: {len(y):,}")
print(f"Target classes: {y.nunique()}")

Feature rows: 2,824,752
Feature columns: 71
Target rows: 2,824,752
Target classes: 15

## 6. Create the train/test split

Use a reproducible stratified 80/20 split so every target class is represented in both subsets. This split estimates performance on held-out flows from the same CIC-IDS-2017 capture; it does not by itself demonstrate generalization to a different network or time period. All later data-dependent preprocessing must be fitted using `X_train` and `y_train` only.

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=y,
)

if not X_train.index.intersection(X_test.index).empty:
    raise AssertionError("Training and test rows overlap.")

del X, y

split_size_summary = pd.DataFrame(
    {
        "Rows": [len(X_train), len(X_test)],
        "Percentage of dataset": [
            len(X_train) / (len(X_train) + len(X_test)) * 100,
            len(X_test) / (len(X_train) + len(X_test)) * 100,
        ],
    },
    index=["Training set", "Test set"],
)
display(split_size_summary)
print(f"Features in each split: {X_train.shape[1]}")

                 Rows  Percentage of dataset
Training set  2259801              79.999979
Test set       564951              20.000021

Features in each split: 71

## 7. Verify split distributions

Confirm that no class disappeared and quantify how closely stratification preserved the original multiclass distribution.

In [7]:
training_label_counts = y_train.value_counts()
test_label_counts = y_test.value_counts()
total_label_counts = (
    training_label_counts.add(test_label_counts, fill_value=0)
    .astype("int64")
    .sort_values(ascending=False)
)

split_label_distribution = pd.DataFrame(
    {
        "Total flows": total_label_counts,
        "Training flows": training_label_counts.reindex(
            total_label_counts.index, fill_value=0
        ),
        "Test flows": test_label_counts.reindex(
            total_label_counts.index, fill_value=0
        ),
    }
)
split_label_distribution["Training percentage"] = (
    split_label_distribution["Training flows"] / len(y_train) * 100
)
split_label_distribution["Test percentage"] = (
    split_label_distribution["Test flows"] / len(y_test) * 100
)
split_label_distribution["Absolute difference (percentage points)"] = (
    split_label_distribution["Training percentage"]
    .sub(split_label_distribution["Test percentage"])
    .abs()
)
display(split_label_distribution)

if split_label_distribution[["Training flows", "Test flows"]].eq(0).any().any():
    raise AssertionError("At least one target class is absent from a split.")

if not (
    split_label_distribution["Training flows"]
    + split_label_distribution["Test flows"]
).equals(split_label_distribution["Total flows"]):
    raise AssertionError("Split label counts do not reproduce the full target.")

print("All 15 classes are present in both splits.")
print("The train/test split is complete; no preprocessing has been fitted.")

,Total flows,Training flows,Test flows,Training percentage,Test percentage,Absolute difference (percentage points)
Label,,,,,,
BENIGN,2268391,1814712,453679,80.304062,80.304133,7.039894e-05
DoS Hulk,229964,183971,45993,8.141027,8.141060,3.344402e-05
PortScan,158804,127043,31761,5.621867,5.621903,3.678832e-05
DDoS,128006,102405,25601,4.531594,4.531543,5.026754e-05
DoS GoldenEye,10288,8230,2058,0.364191,0.364279,8.801977e-05
FTP-Patator,7931,6345,1586,0.280777,0.280732,4.462437e-05
SSH-Patator,5895,4716,1179,0.208691,0.208691,2.770474e-07
DoS slowloris,5796,4637,1159,0.205195,0.205151,4.452403e-05
DoS Slowhttptest,5499,4399,1100,0.194663,0.194707,4.399320e-05
Bot,1956,1565,391,0.069254,0.069210,4.434356e-05
Web Attack - Brute Force,1507,1205,302,0.053323,0.053456,1.326841e-04
Web Attack - XSS,652,522,130,0.023099,0.023011,8.853392e-05
Infiltration,35,28,7,0.001239,0.001239,1.644896e-09
Web Attack - Sql Injection,21,17,4,0.000752,0.000708,4.425262e-05
Heartbleed,7,6,1,0.000266,0.000177,8.850360e-05

All 15 classes are present in both splits.
The train/test split is complete; no preprocessing has been fitted.

## 8. Calculate feature-selection diagnostics

Calculate feature-to-label mutual information and every unique Pearson and Spearman feature pair using only the training data. `Protocol` remains numeric in the data but is treated as discrete by the MI estimator and excluded from Pearson and Spearman because its numeric codes do not represent ordered quantities. Display the MI ranking and one combined correlation table instead of repeating separate Pearson and Spearman outputs.

In [8]:
TOP_CORRELATION_PAIRS_TO_DISPLAY = 100

mi_feature_columns = X_train.columns.tolist()
mi_discrete_feature_mask = [
    column == "Protocol" for column in mi_feature_columns
]

mi_scores = mutual_info_classif(
    X_train[mi_feature_columns],
    y_train,
    discrete_features=mi_discrete_feature_mask,
    random_state=RANDOM_STATE,
    n_jobs=-1,
)

mutual_information_ranking = pd.DataFrame(
    {
        "Feature": mi_feature_columns,
        "Mutual information": mi_scores,
        "MI estimator input type": [
            "Discrete" if is_discrete else "Continuous"
            for is_discrete in mi_discrete_feature_mask
        ],
    }
).sort_values(
    "Mutual information", ascending=False, ignore_index=True
)
mutual_information_ranking.index = pd.RangeIndex(
    start=1,
    stop=len(mutual_information_ranking) + 1,
    name="Rank",
)

correlation_feature_columns = [
    column for column in X_train.columns if column != "Protocol"
]
pearson_correlation_matrix = X_train[
    correlation_feature_columns
].corr(method="pearson")
spearman_correlation_matrix = X_train[
    correlation_feature_columns
].corr(method="spearman")

combined_filter_results = pd.DataFrame(
    (
        (
            first_feature,
            second_feature,
            pearson_correlation_matrix.at[
                first_feature, second_feature
            ],
            spearman_correlation_matrix.at[
                first_feature, second_feature
            ],
        )
        for first_feature, second_feature in combinations(
            correlation_feature_columns, 2
        )
    ),
    columns=[
        "Feature 1",
        "Feature 2",
        "Pearson correlation",
        "Spearman correlation",
    ],
)

mi_score_by_feature = mutual_information_ranking.set_index(
    "Feature"
)["Mutual information"]
combined_filter_results.insert(
    1,
    "Feature 1 MI",
    combined_filter_results["Feature 1"].map(mi_score_by_feature),
)
combined_filter_results.insert(
    3,
    "Feature 2 MI",
    combined_filter_results["Feature 2"].map(mi_score_by_feature),
)
combined_filter_results["Absolute Pearson correlation"] = (
    combined_filter_results["Pearson correlation"].abs()
)
combined_filter_results["Absolute Spearman correlation"] = (
    combined_filter_results["Spearman correlation"].abs()
)
combined_filter_results["Maximum absolute correlation"] = (
    combined_filter_results[
        [
            "Absolute Pearson correlation",
            "Absolute Spearman correlation",
        ]
    ].max(axis=1)
)
combined_filter_results.sort_values(
    "Maximum absolute correlation",
    ascending=False,
    inplace=True,
)
combined_filter_results.index = pd.RangeIndex(
    start=1,
    stop=len(combined_filter_results) + 1,
    name="Pair",
)

combined_filter_display = combined_filter_results.head(
    TOP_CORRELATION_PAIRS_TO_DISPLAY
).copy()
numeric_result_columns = [
    column
    for column in combined_filter_display.columns
    if column not in ["Feature 1", "Feature 2"]
]
combined_filter_display[numeric_result_columns] = (
    combined_filter_display[numeric_result_columns].round(6)
)

print(f"MI features scored: {len(mutual_information_ranking)}")
print(f"Correlation features included: {len(correlation_feature_columns)}")
print(f"Unique correlation pairs checked: {len(combined_filter_results):,}")
print("Mutual-information ranking:")
with pd.option_context("display.max_rows", None):
    display(mutual_information_ranking.round(6))

print(
    f"Top {TOP_CORRELATION_PAIRS_TO_DISPLAY} combined correlation pairs:"
)
with pd.option_context("display.max_rows", None):
    display(combined_filter_display)

MI features scored: 71
Correlation features included: 70
Unique correlation pairs checked: 2,415
Mutual-information ranking:

                         Feature  Mutual information MI estimator input type
Rank
1            Average Packet Size            0.589162              Continuous
2             Packet Length Mean            0.561130              Continuous
3              Packet Length Std            0.558339              Continuous
4         Packet Length Variance            0.556995              Continuous
5              Subflow Bwd Bytes            0.498750              Continuous
6     Total Length of Bwd Packet            0.498369              Continuous
7             FWD Init Win Bytes            0.497415              Continuous
8         Bwd Packet Length Mean            0.490913              Continuous
9           Bwd Segment Size Avg            0.490572              Continuous
10             Subflow Fwd Bytes            0.485743              Continuous
11    Total Length of Fwd Packet            0.485725              Continuous
12         Bwd Packet Length Max            0.457174              Continuous
13             Packet Length Max            0.454000              Continuous
14            Bwd Init Win Bytes            0.448389              Continuous
15         Fwd Packet Length Max            0.439713              Continuous
16                  Flow IAT Max            0.437281              Continuous
17                      Dst Port            0.436298              Continuous
18                  Flow Bytes/s            0.425054              Continuous
19                 Flow Duration            0.423289              Continuous
20                   Fwd IAT Max            0.411720              Continuous
21             Fwd Header Length            0.402117              Continuous
22          Fwd Segment Size Avg            0.401476              Continuous
23        Fwd Packet Length Mean            0.401005              Continuous
24                 Fwd Packets/s            0.397201              Continuous
25                 Fwd IAT Total            0.394418              Continuous
26                Flow Packets/s            0.389709              Continuous
27                 Flow IAT Mean            0.386053              Continuous
28                 Bwd Packets/s            0.384638              Continuous
29             Bwd Header Length            0.380564              Continuous
30                  Fwd IAT Mean            0.380183              Continuous
31              Fwd Seg Size Min            0.348652              Continuous
32         Bwd Packet Length Std            0.324803              Continuous
33         Fwd Packet Length Std            0.316799              Continuous
34                  Flow IAT Std            0.315470              Continuous
35                   Fwd IAT Std            0.293843              Continuous
36                   Bwd IAT Max            0.278824              Continuous
37           Subflow Bwd Packets            0.270831              Continuous
38             Total Bwd packets            0.270560              Continuous
39                 Bwd IAT Total            0.262259              Continuous
40                      Src Port            0.261874              Continuous
41              Total Fwd Packet            0.247153              Continuous
42                  Bwd IAT Mean            0.247068              Continuous
43           Subflow Fwd Packets            0.246821              Continuous
44         Bwd Packet Length Min            0.226311              Continuous
45                 Down/Up Ratio            0.214031              Continuous
46                      Idle Max            0.203883              Continuous
47                      Idle Min            0.200101              Continuous
48                     Idle Mean            0.199806              Continuous
49                   Fwd IAT Min            0.196227              Continuous
50                   Bwd IAT Std            0.194450              Continuous
51                   Active Mean            0.192799              Continuous
52                    Active Max            0.190989              Continuous
53                    Active Min            0.190477              Continuous
54                   Bwd IAT Min            0.186434              Continuous
55             Packet Length Min            0.185119              Continuous
56         Fwd Packet Length Min            0.180397              Continuous
57             Fwd Act Data Pkts            0.172201              Continuous
58                  Flow IAT Min            0.171627              Continuous
59                PSH Flag Count            0.152155              Continuous
60                ACK Flag Count            0.121559              Continuous
61                      Protocol            0.099079                Discrete
62                      Idle Std            0.038311              Continuous
63                FIN Flag Count            0.035941              Continuous
64                URG Flag Count            0.034707              Continuous
65                    Active Std            0.020691              Continuous
66                 Fwd PSH Flags            0.019300              Continuous
67                SYN Flag Count            0.018975              Continuous
68                 Fwd URG Flags            0.000021              Continuous
69                CWR Flag Count            0.000000              Continuous
70                RST Flag Count            0.000000              Continuous
71                ECE Flag Count            0.000000              Continuous

Top 100 combined correlation pairs:

,Feature 1,Feature 1 MI,Feature 2,Feature 2 MI,Pearson correlation,Spearman correlation,Absolute Pearson correlation,Absolute Spearman correlation,Maximum absolute correlation
Pair,,,,,,,,,
1,Bwd Packet Length Mean,0.490913,Bwd Segment Size Avg,0.490572,1.000000,1.000000,1.000000,1.000000,1.000000
2,Total Length of Bwd Packet,0.498369,Subflow Bwd Bytes,0.498750,1.000000,1.000000,1.000000,1.000000,1.000000
3,Total Length of Fwd Packet,0.485725,Subflow Fwd Bytes,0.485743,0.999999,1.000000,0.999999,1.000000,1.000000
4,Total Bwd packets,0.270560,Subflow Bwd Packets,0.270831,1.000000,1.000000,1.000000,1.000000,1.000000
5,Fwd URG Flags,0.000021,CWR Flag Count,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
6,Fwd PSH Flags,0.019300,SYN Flag Count,0.018975,1.000000,1.000000,1.000000,1.000000,1.000000
7,Total Fwd Packet,0.247153,Subflow Fwd Packets,0.246821,1.000000,1.000000,1.000000,1.000000,1.000000
8,Fwd Packet Length Mean,0.401005,Fwd Segment Size Avg,0.401476,1.000000,1.000000,1.000000,1.000000,1.000000
9,Packet Length Std,0.558339,Packet Length Variance,0.556995,0.924830,0.999984,0.924830,0.999984,0.999984
10,Idle Mean,0.199806,Idle Max,0.203883,0.990370,0.999575,0.990370,0.999575,0.999575
11,Active Mean,0.192799,Active Max,0.190989,0.830064,0.999435,0.830064,0.999435,0.999435
12,Idle Mean,0.199806,Idle Min,0.200101,0.990181,0.999172,0.990181,0.999172,0.999172
13,Bwd IAT Mean,0.247068,Bwd IAT Max,0.278824,0.708987,0.998577,0.708987,0.998577,0.998577
14,Flow Duration,0.423289,Fwd IAT Total,0.394418,0.998572,0.725214,0.998572,0.725214,0.998572
15,Idle Max,0.203883,Idle Min,0.200101,0.961706,0.998159,0.961706,0.998159,0.998159
16,Active Mean,0.192799,Active Min,0.190477,0.903426,0.998134,0.903426,0.998134,0.998134
17,Flow IAT Max,0.437281,Fwd IAT Max,0.411720,0.998115,0.701718,0.998115,0.701718,0.998115
18,RST Flag Count,0.000000,ECE Flag Count,0.000000,0.998115,0.998115,0.998115,0.998115,0.998115
19,Bwd IAT Total,0.262259,Bwd IAT Max,0.278824,0.723496,0.998108,0.723496,0.998108,0.998108
20,Packet Length Mean,0.561130,Average Packet Size,0.589162,0.997800,0.996278,0.997800,0.996278,0.997800
21,Bwd IAT Total,0.262259,Bwd IAT Mean,0.247068,0.512687,0.997204,0.512687,0.997204,0.997204
22,Active Max,0.190989,Active Min,0.190477,0.578817,0.996717,0.578817,0.996717,0.996717
23,Fwd IAT Mean,0.380183,Fwd IAT Max,0.411720,0.682789,0.996716,0.682789,0.996716,0.996716
24,Flow Packets/s,0.389709,Flow IAT Mean,0.386053,-0.080398,-0.996700,0.080398,0.996700,0.996700
25,Flow Packets/s,0.389709,Fwd Packets/s,0.397201,0.988950,0.996531,0.988950,0.996531,0.996531
26,Fwd IAT Total,0.394418,Fwd IAT Max,0.411720,0.787150,0.995388,0.787150,0.995388,0.995388
27,Bwd Header Length,0.380564,Subflow Bwd Packets,0.270831,0.994589,0.977542,0.994589,0.977542,0.994589
28,Total Bwd packets,0.270560,Bwd Header Length,0.380564,0.994589,0.977542,0.994589,0.977542,0.994589
29,Fwd IAT Total,0.394418,Fwd IAT Mean,0.380183,0.551221,0.992451,0.551221,0.992451,0.992451
30,Total Fwd Packet,0.247153,Subflow Bwd Packets,0.270831,0.992421,0.636522,0.992421,0.636522,0.992421
31,Total Bwd packets,0.270560,Subflow Fwd Packets,0.246821,0.992421,0.636522,0.992421,0.636522,0.992421
32,Total Fwd Packet,0.247153,Total Bwd packets,0.270560,0.992421,0.636522,0.992421,0.636522,0.992421
33,Subflow Fwd Packets,0.246821,Subflow Bwd Packets,0.270831,0.992421,0.636522,0.992421,0.636522,0.992421
34,Flow IAT Mean,0.386053,Fwd Packets/s,0.397201,-0.074350,-0.992251,0.074350,0.992251,0.992251
35,Flow Duration,0.423289,Flow IAT Max,0.437281,0.785138,0.991306,0.785138,0.991306,0.991306
36,Total Length of Bwd Packet,0.498369,Subflow Bwd Packets,0.270831,0.991177,0.879052,0.991177,0.879052,0.991177
37,Total Bwd packets,0.270560,Total Length of Bwd Packet,0.498369,0.991177,0.879052,0.991177,0.879052,0.991177
38,Subflow Bwd Packets,0.270831,Subflow Bwd Bytes,0.498750,0.991155,0.879052,0.991155,0.879052,0.991155
39,Total Bwd packets,0.270560,Subflow Bwd Bytes,0.498750,0.991155,0.879052,0.991155,0.879052,0.991155
40,Fwd Header Length,0.402117,Subflow Fwd Packets,0.246821,0.989888,0.944705,0.989888,0.944705,0.989888
41,Total Fwd Packet,0.247153,Fwd Header Length,0.402117,0.989888,0.944705,0.989888,0.944705,0.989888
42,Flow Packets/s,0.389709,Flow IAT Max,0.437281,-0.104736,-0.989351,0.104736,0.989351,0.989351
43,Flow IAT Max,0.437281,Idle Max,0.203883,0.989198,0.693181,0.989198,0.693181,0.989198
44,Flow IAT Max,0.437281,Fwd Packets/s,0.397201,-0.096858,-0.988734,0.096858,0.988734,0.988734
45,Fwd IAT Max,0.411720,Idle Max,0.203883,0.988388,0.676833,0.988388,0.676833,0.988388
46,Fwd Packet Length Min,0.180397,Packet Length Min,0.185119,0.441921,0.987098,0.441921,0.987098,0.987098
47,Bwd Header Length,0.380564,Subflow Fwd Packets,0.246821,0.985444,0.632147,0.985444,0.632147,0.985444
48,Total Fwd Packet,0.247153,Bwd Header Length,0.380564,0.985444,0.632147,0.985444,0.632147,0.985444
49,Packet Length Max,0.454000,Packet Length Std,0.558339,0.984600,0.973036,0.984600,0.973036,0.984600
50,Total Length of Bwd Packet,0.498369,Bwd Packet Length Max,0.457174,0.036617,0.983454,0.036617,0.983454,0.983454
51,Bwd Packet Length Max,0.457174,Subflow Bwd Bytes,0.498750,0.036589,0.983454,0.036589,0.983454,0.983454
52,Bwd Packet Length Max,0.457174,Bwd Packet Length Std,0.324803,0.983394,0.761334,0.983394,0.761334,0.983394
53,Bwd Packet Length Max,0.457174,Bwd Segment Size Avg,0.490572,0.959202,0.983023,0.959202,0.983023,0.983023
54,Bwd Packet Length Max,0.457174,Bwd Packet Length Mean,0.490913,0.959202,0.983023,0.959202,0.983023,0.983023
55,Packet Length Max,0.454000,Packet Length Mean,0.561130,0.918208,0.982925,0.918208,0.982925,0.982925
56,Total Fwd Packet,0.247153,Total Length of Bwd Packet,0.498369,0.982504,0.562792,0.982504,0.562792,0.982504
57,Total Length of Bwd Packet,0.498369,Subflow Fwd Packets,0.246821,0.982504,0.562792,0.982504,0.562792,0.982504
58,Subflow Fwd Packets,0.246821,Subflow Bwd Bytes,0.498750,0.982477,0.562792,0.982477,0.562792,0.982477
59,Total Fwd Packet,0.247153,Subflow Bwd Bytes,0.498750,0.982477,0.562792,0.982477,0.562792,0.982477
60,Fwd Header Length,0.402117,Bwd Header Length,0.380564,0.982170,0.655521,0.982170,0.655521,0.982170
61,Flow Duration,0.423289,Flow Packets/s,0.389709,-0.122515,-0.980667,0.122515,0.980667,0.980667
62,Flow Duration,0.423289,Fwd Packets/s,0.397201,-0.113299,-0.980512,0.113299,0.980512,0.980512
63,Total Length of Bwd Packet,0.498369,Bwd Header Length,0.380564,0.980384,0.856529,0.980384,0.856529,0.980384
64,Bwd Header Length,0.380564,Subflow Bwd Bytes,0.498750,0.980352,0.856529,0.980352,0.856529,0.980352
65,Flow IAT Mean,0.386053,Flow IAT Max,0.437281,0.655949,0.979830,0.655949,0.979830,0.979830
66,Flow IAT Max,0.437281,Idle Mean,0.199806,0.979695,0.692878,0.979695,0.692878,0.979695
67,Fwd Header Length,0.402117,Subflow Bwd Packets,0.270831,0.978381,0.632837,0.978381,0.632837,0.978381
68,Total Bwd packets,0.270560,Fwd Header Length,0.402117,0.978381,0.632837,0.978381,0.632837,0.978381
69,Fwd IAT Max,0.411720,Idle Mean,0.199806,0.978123,0.676457,0.978123,0.676457,0.978123
70,Subflow Bwd Bytes,0.498750,Fwd Act Data Pkts,0.172201,0.975712,0.619161,0.975712,0.619161,0.975712
71,Total Length of Bwd Packet,0.498369,Fwd Act Data Pkts,0.172201,0.975698,0.619161,0.975698,0.619161,0.975698
72,Packet Length Max,0.454000,Average Packet Size,0.589162,0.912881,0.973878,0.912881,0.973878,0.973878
73,Packet Length Max,0.454000,Packet Length Variance,0.556995,0.896057,0.973054,0.896057,0.973054,0.973054
74,Total Bwd packets,0.270560,Fwd Act Data Pkts,0.172201,0.972013,0.679678,0.972013,0.679678,0.972013
75,Subflow Bwd Packets,0.270831,Fwd Act Data Pkts,0.172201,0.972013,0.679678,0.972013,0.679678,0.972013
76,Subflow Fwd Packets,0.246821,Fwd Act Data Pkts,0.172201,0.970807,0.878998,0.970807,0.878998,0.970807
77,Total Fwd Packet,0.247153,Fwd Act Data Pkts,0.172201,0.970807,0.878998,0.970807,0.878998,0.970807
78,Bwd Segment Size Avg,0.490572,Subflow Bwd Bytes,0.498750,0.042041,0.970771,0.042041,0.970771,0.970771
79,Total Length of Bwd Packet,0.498369,Bwd Segment Size Avg,0.490572,0.042075,0.970771,0.042075,0.970771,0.970771
80,Bwd Packet Length Mean,0.490913,Subflow Bwd Bytes,0.498750,0.042041,0.970771,0.042041,0.970771,0.970771
81,Total Length of Bwd Packet,0.498369,Bwd Packet Length Mean,0.490913,0.042075,0.970771,0.042075,0.970771,0.970771
82,Flow Duration,0.423289,Flow IAT Mean,0.386053,0.537458,0.969018,0.537458,0.969018,0.969018
83,Fwd Packet Length Max,0.439713,Fwd Packet Length Std,0.316799,0.968888,0.702317,0.968888,0.702317,0.968888
84,Active Min,0.190477,Idle Min,0.200101,0.113589,0.966753,0.113589,0.966753,0.966753
85,Active Min,0.190477,Idle Mean,0.199806,0.118953,0.966170,0.118953,0.966170,0.966170
86,Active Mean,0.192799,Idle Min,0.200101,0.110308,0.966006,0.110308,0.966006,0.966006
87,Active Mean,0.192799,Idle Mean,0.199806,0.120727,0.965872,0.120727,0.965872,0.965872
88,Active Max,0.190989,Idle Max,0.203883,0.102727,0.965779,0.102727,0.965779,0.965779
89,Active Mean,0.192799,Idle Max,0.203883,0.133444,0.965757,0.133444,0.965757,0.965757
90,Active Min,0.190477,Idle Max,0.203883,0.123596,0.965748,0.123596,0.965748,0.965748
91,Active Max,0.190989,Idle Mean,0.199806,0.088732,0.965712,0.088732,0.965712,0.965712
92,Active Max,0.190989,Idle Min,0.200101,0.077050,0.965660,0.077050,0.965660,0.965660
93,Total Length of Bwd Packet,0.498369,Fwd Header Length,0.402117,0.960740,0.560215,0.960740,0.560215,0.960740
94,Fwd Header Length,0.402117,Subflow Bwd Bytes,0.498750,0.960690,0.560215,0.960690,0.560215,0.960690
95,Flow IAT Max,0.437281,Idle Min,0.200101,0.951390,0.691830,0.951390,0.691830,0.951390
96,Bwd Header Length,0.380564,Fwd Act Data Pkts,0.172201,0.951040,0.658730,0.951040,0.658730,0.951040
97,Fwd IAT Max,0.411720,Idle Min,0.200101,0.949036,0.674756,0.949036,0.674756,0.949036
98,Bwd Packet Length Max,0.457174,Packet Length Max,0.454000,0.948345,0.940042,0.948345,0.940042,0.948345
99,Fwd Packet Length Max,0.439713,Fwd Packet Length Mean,0.401005,0.888242,0.946426,0.888242,0.946426,0.946426
100,Fwd Packet Length Max,0.439713,Fwd Segment Size Avg,0.401476,0.888242,0.946426,0.888242,0.946426,0.946426

The calculations cover all 71 features for MI and all 2,415 unique pairs among the 70 non-`Protocol` features for correlation. MI is a univariate relevance diagnostic, while Pearson and Spearman identify linear and monotonic relationships between features. Neither measurement authorizes removal by itself: highly associated features can describe different network behavior, and globally low MI can overlook features that help detect rare classes. The combined output is therefore an audit used to support explicit decisions rather than an automatic threshold rule.

## 9. Document and validate manually reviewed redundancy decisions

Document the seven features selected for later removal after reviewing their definitions, observed values, mutual information and pairwise relationships. Validate that every feature and retained counterpart exists and attach the training-set correlation and MI evidence. This section records the decisions without modifying either data split.

In [9]:
features_to_remove = [
    "Fwd Segment Size Avg",
    "Bwd Segment Size Avg",
    "Subflow Fwd Packets",
    "Subflow Bwd Packets",
    "Subflow Fwd Bytes",
    "Subflow Bwd Bytes",
    "Packet Length Variance",
]

feature_removal_decisions = pd.DataFrame(
    {
        "Remove": features_to_remove,
        "Retain instead": [
            "Fwd Packet Length Mean",
            "Bwd Packet Length Mean",
            "Total Fwd Packet",
            "Total Bwd packets",
            "Total Length of Fwd Packet",
            "Total Length of Bwd Packet",
            "Packet Length Std",
        ],
        "Reason": [
            "Same practical values apart from floating-point noise",
            "Same practical values apart from rounding noise",
            "Identical throughout the training data",
            "Identical throughout the training data",
            "Differs in only one training row",
            "Differs in only 16 training rows",
            "Near-monotonic transformed representation of standard deviation",
        ],
    }
)
missing_removal_features = [
    feature
    for feature in features_to_remove
    if feature not in X_train.columns
]
if missing_removal_features:
    raise KeyError(
        "Expected removal features are missing: "
        f"{missing_removal_features}"
    )

missing_retained_features = [
    feature
    for feature in feature_removal_decisions["Retain instead"]
    if feature not in X_train.columns
]
if missing_retained_features:
    raise KeyError(
        "Expected retained features are missing: "
        f"{missing_retained_features}"
    )

decision_evidence = []
for _, decision in feature_removal_decisions.iterrows():
    remove_feature = decision["Remove"]
    retain_feature = decision["Retain instead"]
    matching_relationship = combined_filter_results.loc[
        (
            (combined_filter_results["Feature 1"] == remove_feature)
            & (combined_filter_results["Feature 2"] == retain_feature)
        )
        | (
            (combined_filter_results["Feature 1"] == retain_feature)
            & (combined_filter_results["Feature 2"] == remove_feature)
        )
    ]
    if len(matching_relationship) != 1:
        raise AssertionError(
            "Expected one correlation relationship for "
            f"{remove_feature} and {retain_feature}."
        )

    relationship = matching_relationship.iloc[0]
    decision_evidence.append(
        {
            "Remove MI": mi_score_by_feature[remove_feature],
            "Retain MI": mi_score_by_feature[retain_feature],
            "Pearson correlation": relationship[
                "Pearson correlation"
            ],
            "Spearman correlation": relationship[
                "Spearman correlation"
            ],
        }
    )

feature_removal_decisions = pd.concat(
    [
        feature_removal_decisions,
        pd.DataFrame(decision_evidence),
    ],
    axis=1,
)
display(feature_removal_decisions.round(6))

print(f"Documented decisions: {len(feature_removal_decisions)}")
print("All removal and retained features were validated.")
print("X_train and X_test remain unchanged.")

,Remove,Retain instead,Reason,Remove MI,Retain MI,Pearson correlation,Spearman correlation
0,Fwd Segment Size Avg,Fwd Packet Length Mean,Same practical values apart from floating-poin...,0.401476,0.401005,1.000000,1.000000
1,Bwd Segment Size Avg,Bwd Packet Length Mean,Same practical values apart from rounding noise,0.490572,0.490913,1.000000,1.000000
2,Subflow Fwd Packets,Total Fwd Packet,Identical throughout the training data,0.246821,0.247153,1.000000,1.000000
3,Subflow Bwd Packets,Total Bwd packets,Identical throughout the training data,0.270831,0.270560,1.000000,1.000000
4,Subflow Fwd Bytes,Total Length of Fwd Packet,Differs in only one training row,0.485743,0.485725,0.999999,1.000000
5,Subflow Bwd Bytes,Total Length of Bwd Packet,Differs in only 16 training rows,0.498750,0.498369,1.000000,1.000000
6,Packet Length Variance,Packet Length Std,Near-monotonic transformed representation of s...,0.556995,0.558339,0.924830,0.999984

Documented decisions: 7
All removal and retained features were validated.
X_train and X_test remain unchanged.

All seven decisions are documented with their retained counterparts, reasons, MI scores and Pearson/Spearman relationships. The validation confirms that every referenced column and pair is present. No columns are removed here, and both `X_train` and `X_test` remain unchanged with 71 features.