# CIC-IDS-2017 feature preparation

This notebook starts from the cleaned dataset produced by `01_data_exploration.ipynb`. Its first stage removes identifier columns that would encourage memorization of the CIC-IDS-2017 laboratory, separates the remaining features from the multiclass target, and creates a reproducible stratified train/test split. No scaling, encoding, correlation filtering, resampling or learned feature selection is performed before the split.

## 1. Imports and paths

In [1]:
from itertools import combinations
from pathlib import Path

import pandas as pd
from IPython.display import display
from sklearn.feature_selection import mutual_info_classif
from sklearn.model_selection import train_test_split

processed_dataset_candidates = [
    Path("../data/processed/cicids2017_cleaned.parquet"),
    Path("ml/data/processed/cicids2017_cleaned.parquet"),
]

PROCESSED_DATA_PATH = next(
    (
        path.resolve()
        for path in processed_dataset_candidates
        if path.exists()
    ),
    None,
)

if PROCESSED_DATA_PATH is None:
    raise FileNotFoundError(
        "Could not find cicids2017_cleaned.parquet. "
        "Run 01_data_exploration.ipynb first."
    )

RANDOM_STATE = 42
TEST_SIZE = 0.20

print(f"Processed dataset: {PROCESSED_DATA_PATH}")
print(f"File size: {PROCESSED_DATA_PATH.stat().st_size / (1024 ** 2):,.2f} MiB")
print(f"Random state: {RANDOM_STATE}")
print(f"Test fraction: {TEST_SIZE:.0%}")

Processed dataset: C:\Users\ademz\Desktop\9raya\DoS-Intrusion-Detection-System\ml\data\processed\cicids2017_cleaned.parquet
File size: 360.48 MiB
Random state: 42
Test fraction: 20%

## 2. Load and validate the cleaned data

Confirm that the processed file matches the final dimensions and target structure recorded in the exploration notebook.

In [2]:
data = pd.read_parquet(PROCESSED_DATA_PATH)

EXPECTED_ROWS = 2_824_752
EXPECTED_COLUMNS = 76
EXPECTED_LABELS = 15

dataset_validation = pd.DataFrame(
    {
        "Observed": [
            data.shape[0],
            data.shape[1],
            data["Label"].nunique(dropna=False)
            if "Label" in data.columns
            else 0,
            int(data["Label"].isna().sum())
            if "Label" in data.columns
            else data.shape[0],
        ],
        "Expected": [
            EXPECTED_ROWS,
            EXPECTED_COLUMNS,
            EXPECTED_LABELS,
            0,
        ],
    },
    index=[
        "Rows",
        "Columns",
        "Detailed target classes",
        "Missing target labels",
    ],
)
display(dataset_validation)

if not dataset_validation["Observed"].equals(
    dataset_validation["Expected"]
):
    raise AssertionError(
        "The cleaned dataset does not match the expected EDA output."
    )

print("The cleaned dataset matches the final EDA output.")

                         Observed  Expected
Rows                      2824752   2824752
Columns                        76        76
Detailed target classes        15        15
Missing target labels           0         0

The cleaned dataset matches the final EDA output.

## 3. Review all cleaned columns

Display the complete cleaned schema before excluding identifiers or separating the target.

In [3]:
cleaned_column_overview = pd.DataFrame(
    {
        "Position": range(1, len(data.columns) + 1),
        "Column": data.columns,
        "Data type": data.dtypes.astype(str).to_numpy(),
    }
).set_index("Position")

with pd.option_context("display.max_rows", None):
    display(cleaned_column_overview)
print(f"Total cleaned columns: {len(cleaned_column_overview)}")

                              Column Data type
Position
1                            Flow ID    object
2                             Src IP    object
3                           Src Port   float64
4                             Dst IP    object
5                           Dst Port   float64
6                           Protocol   float64
7                          Timestamp    object
8                      Flow Duration   float64
9                   Total Fwd Packet   float64
10                 Total Bwd packets   float64
11        Total Length of Fwd Packet   float64
12        Total Length of Bwd Packet   float64
13             Fwd Packet Length Max   float64
14             Fwd Packet Length Min   float64
15            Fwd Packet Length Mean   float64
16             Fwd Packet Length Std   float64
17             Bwd Packet Length Max   float64
18             Bwd Packet Length Min   float64
19            Bwd Packet Length Mean   float64
20             Bwd Packet Length Std   float64
21                      Flow Bytes/s   float64
22                    Flow Packets/s   float64
23                     Flow IAT Mean   float64
24                      Flow IAT Std   float64
25                      Flow IAT Max   float64
26                      Flow IAT Min   float64
27                     Fwd IAT Total   float64
28                      Fwd IAT Mean   float64
29                       Fwd IAT Std   float64
30                       Fwd IAT Max   float64
31                       Fwd IAT Min   float64
32                     Bwd IAT Total   float64
33                      Bwd IAT Mean   float64
34                       Bwd IAT Std   float64
35                       Bwd IAT Max   float64
36                       Bwd IAT Min   float64
37                     Fwd PSH Flags   float64
38                     Fwd URG Flags   float64
39                 Fwd Header Length   float64
40                 Bwd Header Length   float64
41                     Fwd Packets/s   float64
42                     Bwd Packets/s   float64
43                 Packet Length Min   float64
44                 Packet Length Max   float64
45                Packet Length Mean   float64
46                 Packet Length Std   float64
47            Packet Length Variance   float64
48                    FIN Flag Count   float64
49                    SYN Flag Count   float64
50                    RST Flag Count   float64
51                    PSH Flag Count   float64
52                    ACK Flag Count   float64
53                    URG Flag Count   float64
54                    CWR Flag Count   float64
55                    ECE Flag Count   float64
56                     Down/Up Ratio   float64
57               Average Packet Size   float64
58              Fwd Segment Size Avg   float64
59              Bwd Segment Size Avg   float64
60               Subflow Fwd Packets   float64
61                 Subflow Fwd Bytes   float64
62               Subflow Bwd Packets   float64
63                 Subflow Bwd Bytes   float64
64                FWD Init Win Bytes   float64
65                Bwd Init Win Bytes   float64
66                 Fwd Act Data Pkts   float64
67                  Fwd Seg Size Min   float64
68                       Active Mean   float64
69                        Active Std   float64
70                        Active Max   float64
71                        Active Min   float64
72                         Idle Mean   float64
73                          Idle Std   float64
74                          Idle Max   float64
75                          Idle Min   float64
76                             Label    object

Total cleaned columns: 76

## 4. Remove identifier and leakage-prone columns

`Flow ID`, endpoint IP addresses and `Timestamp` describe this particular laboratory capture rather than transferable flow behavior. These fixed schema exclusions do not depend on statistics calculated from the dataset, so remove them directly from the cleaned table before separating features and target. Ports and `Protocol` are retained for now.

In [4]:
identifier_columns = [
    "Flow ID",
    "Src IP",
    "Dst IP",
    "Timestamp",
]
missing_identifier_columns = [
    column for column in identifier_columns if column not in data.columns
]
if missing_identifier_columns:
    raise KeyError(
        "Expected identifier columns are missing: "
        f"{missing_identifier_columns}"
    )

identifier_decisions = pd.DataFrame(
    {
        "Column": identifier_columns,
        "Reason for exclusion": [
            "Constructed flow identifier; encourages record memorization",
            "Source identity is specific to the CIC-IDS-2017 laboratory",
            "Destination identity is specific to the CIC-IDS-2017 laboratory",
            "Encodes the published attack schedule and capture day",
        ],
    }
)
display(identifier_decisions)

data.drop(columns=identifier_columns, inplace=True)
print(f"Columns remaining after fixed exclusions: {data.shape[1]}")

      Column                               Reason for exclusion
0    Flow ID  Constructed flow identifier; encourages record...
1     Src IP  Source identity is specific to the CIC-IDS-201...
2     Dst IP  Destination identity is specific to the CIC-ID...
3  Timestamp  Encodes the published attack schedule and capt...

Columns remaining after fixed exclusions: 72

## 5. Separate features and target

Keep the original 15-class `Label` as the target. Using `pop` separates it without duplicating the large feature table in memory.

In [5]:
y = data.pop("Label")
X = data
del data

print(f"Feature rows: {X.shape[0]:,}")
print(f"Feature columns: {X.shape[1]}")
print(f"Target rows: {len(y):,}")
print(f"Target classes: {y.nunique()}")

Feature rows: 2,824,752
Feature columns: 71
Target rows: 2,824,752
Target classes: 15

## 6. Inspect Protocol values

Start by displaying the unmodified `Protocol.value_counts()` result. Assign readable names only after the values actually present in the cleaned dataset are visible. The stored `Protocol` column is not changed in this section.

In [6]:
raw_protocol_counts = (
    X["Protocol"].value_counts(dropna=False).sort_index()
)
raw_protocol_distribution = (
    raw_protocol_counts
    .rename_axis("Raw Protocol value")
    .rename("Flow count")
    .to_frame()
)
raw_protocol_distribution["Percentage of dataset"] = (
    raw_protocol_distribution["Flow count"] / len(X) * 100
)
display(raw_protocol_distribution)

                    Flow count  Percentage of dataset
Raw Protocol value
0.0                       1696               0.060041
6.0                    1823631              64.558977
17.0                    999425              35.380982

The observed protocol values and their names are:

- `0`: HOPOPT
- `6`: TCP
- `17`: UDP

The notebook leaves the `Protocol` column unchanged. `Label` is the target rather than a feature, and the representation of source and destination ports remains a later feature-engineering decision.

## 7. Create the train/test split

Use a reproducible stratified 80/20 split so every target class is represented in both subsets. This split estimates performance on held-out flows from the same CIC-IDS-2017 capture; it does not by itself demonstrate generalization to a different network or time period. All later data-dependent preprocessing must be fitted using `X_train` and `y_train` only.

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=y,
)

if not X_train.index.intersection(X_test.index).empty:
    raise AssertionError("Training and test rows overlap.")

del X, y

split_size_summary = pd.DataFrame(
    {
        "Rows": [len(X_train), len(X_test)],
        "Percentage of dataset": [
            len(X_train) / (len(X_train) + len(X_test)) * 100,
            len(X_test) / (len(X_train) + len(X_test)) * 100,
        ],
    },
    index=["Training set", "Test set"],
)
display(split_size_summary)
print(f"Features in each split: {X_train.shape[1]}")

                 Rows  Percentage of dataset
Training set  2259801              79.999979
Test set       564951              20.000021

Features in each split: 71

## 8. Verify split distributions

Confirm that no class disappeared and quantify how closely stratification preserved the original multiclass distribution.

In [8]:
training_label_counts = y_train.value_counts()
test_label_counts = y_test.value_counts()
total_label_counts = (
    training_label_counts.add(test_label_counts, fill_value=0)
    .astype("int64")
    .sort_values(ascending=False)
)

split_label_distribution = pd.DataFrame(
    {
        "Total flows": total_label_counts,
        "Training flows": training_label_counts.reindex(
            total_label_counts.index, fill_value=0
        ),
        "Test flows": test_label_counts.reindex(
            total_label_counts.index, fill_value=0
        ),
    }
)
split_label_distribution["Training percentage"] = (
    split_label_distribution["Training flows"] / len(y_train) * 100
)
split_label_distribution["Test percentage"] = (
    split_label_distribution["Test flows"] / len(y_test) * 100
)
split_label_distribution["Absolute difference (percentage points)"] = (
    split_label_distribution["Training percentage"]
    .sub(split_label_distribution["Test percentage"])
    .abs()
)
display(split_label_distribution)

if split_label_distribution[["Training flows", "Test flows"]].eq(0).any().any():
    raise AssertionError("At least one target class is absent from a split.")

if not (
    split_label_distribution["Training flows"]
    + split_label_distribution["Test flows"]
).equals(split_label_distribution["Total flows"]):
    raise AssertionError("Split label counts do not reproduce the full target.")

print("All 15 classes are present in both splits.")
print("The train/test split is complete; no preprocessing has been fitted.")

,Total flows,Training flows,Test flows,Training percentage,Test percentage,Absolute difference (percentage points)
Label,,,,,,
BENIGN,2268391,1814712,453679,80.304062,80.304133,7.039894e-05
DoS Hulk,229964,183971,45993,8.141027,8.141060,3.344402e-05
PortScan,158804,127043,31761,5.621867,5.621903,3.678832e-05
DDoS,128006,102405,25601,4.531594,4.531543,5.026754e-05
DoS GoldenEye,10288,8230,2058,0.364191,0.364279,8.801977e-05
FTP-Patator,7931,6345,1586,0.280777,0.280732,4.462437e-05
SSH-Patator,5895,4716,1179,0.208691,0.208691,2.770474e-07
DoS slowloris,5796,4637,1159,0.205195,0.205151,4.452403e-05
DoS Slowhttptest,5499,4399,1100,0.194663,0.194707,4.399320e-05
Bot,1956,1565,391,0.069254,0.069210,4.434356e-05
Web Attack - Brute Force,1507,1205,302,0.053323,0.053456,1.326841e-04
Web Attack - XSS,652,522,130,0.023099,0.023011,8.853392e-05
Infiltration,35,28,7,0.001239,0.001239,1.644896e-09
Web Attack - Sql Injection,21,17,4,0.000752,0.000708,4.425262e-05
Heartbleed,7,6,1,0.000266,0.000177,8.850360e-05

All 15 classes are present in both splits.
The train/test split is complete; no preprocessing has been fitted.

## 9. Calculate feature-to-label mutual information

Calculate mutual information between every feature in `X_train` and the multiclass target `y_train`. `Protocol` is identified as discrete only for the estimator; its stored dtype and values remain unchanged. Display the complete ranking without selecting or removing features.

In [9]:
mi_feature_columns = X_train.columns.tolist()
mi_discrete_feature_mask = [
    column == "Protocol" for column in mi_feature_columns
]

mi_scores = mutual_info_classif(
    X_train[mi_feature_columns],
    y_train,
    discrete_features=mi_discrete_feature_mask,
    random_state=RANDOM_STATE,
    n_jobs=-1,
)

mutual_information_ranking = pd.DataFrame(
    {
        "Feature": mi_feature_columns,
        "Mutual information": mi_scores,
        "MI estimator input type": [
            "Discrete" if is_discrete else "Continuous"
            for is_discrete in mi_discrete_feature_mask
        ],
    }
).sort_values(
    "Mutual information", ascending=False, ignore_index=True
)
mutual_information_ranking.index = pd.RangeIndex(
    start=1,
    stop=len(mutual_information_ranking) + 1,
    name="Rank",
)

print(f"Features scored: {len(mutual_information_ranking)}")
with pd.option_context("display.max_rows", None):
    display(mutual_information_ranking)

Features scored: 71

                         Feature  Mutual information MI estimator input type
Rank
1            Average Packet Size            0.589162              Continuous
2             Packet Length Mean            0.561130              Continuous
3              Packet Length Std            0.558339              Continuous
4         Packet Length Variance            0.556995              Continuous
5              Subflow Bwd Bytes            0.498750              Continuous
6     Total Length of Bwd Packet            0.498369              Continuous
7             FWD Init Win Bytes            0.497415              Continuous
8         Bwd Packet Length Mean            0.490913              Continuous
9           Bwd Segment Size Avg            0.490572              Continuous
10             Subflow Fwd Bytes            0.485743              Continuous
11    Total Length of Fwd Packet            0.485725              Continuous
12         Bwd Packet Length Max            0.457174              Continuous
13             Packet Length Max            0.454000              Continuous
14            Bwd Init Win Bytes            0.448389              Continuous
15         Fwd Packet Length Max            0.439713              Continuous
16                  Flow IAT Max            0.437281              Continuous
17                      Dst Port            0.436298              Continuous
18                  Flow Bytes/s            0.425054              Continuous
19                 Flow Duration            0.423289              Continuous
20                   Fwd IAT Max            0.411720              Continuous
21             Fwd Header Length            0.402117              Continuous
22          Fwd Segment Size Avg            0.401476              Continuous
23        Fwd Packet Length Mean            0.401005              Continuous
24                 Fwd Packets/s            0.397201              Continuous
25                 Fwd IAT Total            0.394418              Continuous
26                Flow Packets/s            0.389709              Continuous
27                 Flow IAT Mean            0.386053              Continuous
28                 Bwd Packets/s            0.384638              Continuous
29             Bwd Header Length            0.380564              Continuous
30                  Fwd IAT Mean            0.380183              Continuous
31              Fwd Seg Size Min            0.348652              Continuous
32         Bwd Packet Length Std            0.324803              Continuous
33         Fwd Packet Length Std            0.316799              Continuous
34                  Flow IAT Std            0.315470              Continuous
35                   Fwd IAT Std            0.293843              Continuous
36                   Bwd IAT Max            0.278824              Continuous
37           Subflow Bwd Packets            0.270831              Continuous
38             Total Bwd packets            0.270560              Continuous
39                 Bwd IAT Total            0.262259              Continuous
40                      Src Port            0.261874              Continuous
41              Total Fwd Packet            0.247153              Continuous
42                  Bwd IAT Mean            0.247068              Continuous
43           Subflow Fwd Packets            0.246821              Continuous
44         Bwd Packet Length Min            0.226311              Continuous
45                 Down/Up Ratio            0.214031              Continuous
46                      Idle Max            0.203883              Continuous
47                      Idle Min            0.200101              Continuous
48                     Idle Mean            0.199806              Continuous
49                   Fwd IAT Min            0.196227              Continuous
50                   Bwd IAT Std            0.194450              Continuous
51                   Active Mean            0.192799              Continuous
52                    Active Max            0.190989              Continuous
53                    Active Min            0.190477              Continuous
54                   Bwd IAT Min            0.186434              Continuous
55             Packet Length Min            0.185119              Continuous
56         Fwd Packet Length Min            0.180397              Continuous
57             Fwd Act Data Pkts            0.172201              Continuous
58                  Flow IAT Min            0.171627              Continuous
59                PSH Flag Count            0.152155              Continuous
60                ACK Flag Count            0.121559              Continuous
61                      Protocol            0.099079                Discrete
62                      Idle Std            0.038311              Continuous
63                FIN Flag Count            0.035941              Continuous
64                URG Flag Count            0.034707              Continuous
65                    Active Std            0.020691              Continuous
66                 Fwd PSH Flags            0.019300              Continuous
67                SYN Flag Count            0.018975              Continuous
68                 Fwd URG Flags            0.000021              Continuous
69                CWR Flag Count            0.000000              Continuous
70                RST Flag Count            0.000000              Continuous
71                ECE Flag Count            0.000000              Continuous

The highest MI scores belong mainly to overall packet-length statistics, transferred-byte features, TCP initial-window values and timing/rate features. `Average Packet Size` ranks first (`0.589`), followed by `Packet Length Mean`, `Packet Length Std` and `Packet Length Variance`. Several known related features receive almost equal scores, such as total and subflow byte values and directional packet-length means and segment-size averages. `Protocol` ranks 61st (`0.099`). The lowest scores belong mostly to sparse flag counters, with `CWR Flag Count`, `RST Flag Count` and `ECE Flag Count` estimated at zero. These scores provide a ranking, not a removal threshold; global MI can undervalue signals associated only with the rarest classes.

## 10. Calculate Pearson feature correlations

Calculate Pearson correlations using `X_train` only. Exclude `Protocol` because its numeric values are protocol identifiers rather than continuous measurements. Calculate every unique pair, but display only the top 100 in descending order of absolute correlation. The table is an inspection aid: correlation alone does not authorize removing either feature.

In [10]:
TOP_CORRELATION_PAIRS_TO_DISPLAY = 100
correlation_feature_columns = [
    column for column in X_train.columns if column != "Protocol"
]

pearson_correlation_matrix = X_train[
    correlation_feature_columns
].corr(method="pearson")

pearson_correlation_pairs = pd.DataFrame(
    (
        (
            first_feature,
            second_feature,
            pearson_correlation_matrix.at[
                first_feature, second_feature
            ],
        )
        for first_feature, second_feature in combinations(
            correlation_feature_columns, 2
        )
    ),
    columns=["Feature 1", "Feature 2", "Pearson correlation"],
)
pearson_correlation_pairs["Absolute correlation"] = (
    pearson_correlation_pairs["Pearson correlation"].abs()
)
pearson_correlation_pairs.sort_values(
    "Absolute correlation", ascending=False, inplace=True
)
pearson_correlation_pairs.index = pd.RangeIndex(
    start=1,
    stop=len(pearson_correlation_pairs) + 1,
    name="Pair",
)

print(f"Training features included: {len(correlation_feature_columns)}")
print(f"Unique feature pairs checked: {len(pearson_correlation_pairs):,}")
print(f"Top {TOP_CORRELATION_PAIRS_TO_DISPLAY} pairs are displayed below.")

pearson_correlation_display = pearson_correlation_pairs.head(
    TOP_CORRELATION_PAIRS_TO_DISPLAY
).copy()
pearson_correlation_display["Pearson correlation"] = (
    pearson_correlation_display["Pearson correlation"].round(6)
)
pearson_correlation_display["Absolute correlation"] = (
    pearson_correlation_display["Absolute correlation"].round(6)
)
with pd.option_context("display.max_rows", None):
    display(pearson_correlation_display)

Training features included: 70
Unique feature pairs checked: 2,415
Top 100 pairs are displayed below.

,Feature 1,Feature 2,Pearson correlation,Absolute correlation
Pair,,,,
1,Bwd Packet Length Mean,Bwd Segment Size Avg,1.000000,1.000000
2,Fwd URG Flags,CWR Flag Count,1.000000,1.000000
3,Total Fwd Packet,Subflow Fwd Packets,1.000000,1.000000
4,Fwd Packet Length Mean,Fwd Segment Size Avg,1.000000,1.000000
5,Fwd PSH Flags,SYN Flag Count,1.000000,1.000000
6,Total Bwd packets,Subflow Bwd Packets,1.000000,1.000000
7,Total Length of Bwd Packet,Subflow Bwd Bytes,1.000000,1.000000
8,Total Length of Fwd Packet,Subflow Fwd Bytes,0.999999,0.999999
9,Flow Duration,Fwd IAT Total,0.998572,0.998572
10,Flow IAT Max,Fwd IAT Max,0.998115,0.998115
11,RST Flag Count,ECE Flag Count,0.998115,0.998115
12,Packet Length Mean,Average Packet Size,0.997800,0.997800
13,Bwd Header Length,Subflow Bwd Packets,0.994589,0.994589
14,Total Bwd packets,Bwd Header Length,0.994589,0.994589
15,Total Fwd Packet,Subflow Bwd Packets,0.992421,0.992421
16,Total Bwd packets,Subflow Fwd Packets,0.992421,0.992421
17,Subflow Fwd Packets,Subflow Bwd Packets,0.992421,0.992421
18,Total Fwd Packet,Total Bwd packets,0.992421,0.992421
19,Total Bwd packets,Total Length of Bwd Packet,0.991177,0.991177
20,Total Length of Bwd Packet,Subflow Bwd Packets,0.991177,0.991177
21,Subflow Bwd Packets,Subflow Bwd Bytes,0.991155,0.991155
22,Total Bwd packets,Subflow Bwd Bytes,0.991155,0.991155
23,Idle Mean,Idle Max,0.990370,0.990370
24,Idle Mean,Idle Min,0.990181,0.990181
25,Fwd Header Length,Subflow Fwd Packets,0.989888,0.989888
26,Total Fwd Packet,Fwd Header Length,0.989888,0.989888
27,Flow IAT Max,Idle Max,0.989198,0.989198
28,Flow Packets/s,Fwd Packets/s,0.988950,0.988950
29,Fwd IAT Max,Idle Max,0.988388,0.988388
30,Total Fwd Packet,Bwd Header Length,0.985444,0.985444
31,Bwd Header Length,Subflow Fwd Packets,0.985444,0.985444
32,Packet Length Max,Packet Length Std,0.984600,0.984600
33,Bwd Packet Length Max,Bwd Packet Length Std,0.983394,0.983394
34,Total Fwd Packet,Total Length of Bwd Packet,0.982504,0.982504
35,Total Length of Bwd Packet,Subflow Fwd Packets,0.982504,0.982504
36,Subflow Fwd Packets,Subflow Bwd Bytes,0.982477,0.982477
37,Total Fwd Packet,Subflow Bwd Bytes,0.982477,0.982477
38,Fwd Header Length,Bwd Header Length,0.982170,0.982170
39,Total Length of Bwd Packet,Bwd Header Length,0.980384,0.980384
40,Bwd Header Length,Subflow Bwd Bytes,0.980352,0.980352
41,Flow IAT Max,Idle Mean,0.979695,0.979695
42,Total Bwd packets,Fwd Header Length,0.978381,0.978381
43,Fwd Header Length,Subflow Bwd Packets,0.978381,0.978381
44,Fwd IAT Max,Idle Mean,0.978123,0.978123
45,Subflow Bwd Bytes,Fwd Act Data Pkts,0.975712,0.975712
46,Total Length of Bwd Packet,Fwd Act Data Pkts,0.975698,0.975698
47,Total Bwd packets,Fwd Act Data Pkts,0.972013,0.972013
48,Subflow Bwd Packets,Fwd Act Data Pkts,0.972013,0.972013
49,Subflow Fwd Packets,Fwd Act Data Pkts,0.970807,0.970807
50,Total Fwd Packet,Fwd Act Data Pkts,0.970807,0.970807
51,Fwd Packet Length Max,Fwd Packet Length Std,0.968888,0.968888
52,Idle Max,Idle Min,0.961706,0.961706
53,Total Length of Bwd Packet,Fwd Header Length,0.960740,0.960740
54,Fwd Header Length,Subflow Bwd Bytes,0.960690,0.960690
55,Bwd Packet Length Max,Bwd Packet Length Mean,0.959202,0.959202
56,Bwd Packet Length Max,Bwd Segment Size Avg,0.959202,0.959202
57,Flow IAT Max,Idle Min,0.951390,0.951390
58,Bwd Header Length,Fwd Act Data Pkts,0.951040,0.951040
59,Fwd IAT Max,Idle Min,0.949036,0.949036
60,Bwd Packet Length Max,Packet Length Max,0.948345,0.948345
61,Packet Length Mean,Packet Length Std,0.944292,0.944292
62,Packet Length Std,Average Packet Size,0.944018,0.944018
63,Bwd Packet Length Std,Packet Length Std,0.942626,0.942626
64,Bwd Packet Length Mean,Bwd Packet Length Std,0.942460,0.942460
65,Bwd Packet Length Std,Bwd Segment Size Avg,0.942460,0.942460
66,Bwd Packet Length Max,Packet Length Std,0.940311,0.940311
67,Flow IAT Std,Flow IAT Max,0.938421,0.938421
68,Fwd Header Length,Fwd Act Data Pkts,0.936937,0.936937
69,Flow IAT Std,Fwd IAT Max,0.936472,0.936472
70,Flow IAT Std,Idle Max,0.935923,0.935923
71,Bwd Packet Length Std,Packet Length Max,0.933239,0.933239
72,Bwd IAT Mean,Bwd IAT Min,0.932780,0.932780
73,Flow IAT Std,Idle Mean,0.931650,0.931650
74,Packet Length Std,Packet Length Variance,0.924830,0.924830
75,Packet Length Mean,Bwd Segment Size Avg,0.922285,0.922285
76,Bwd Packet Length Mean,Packet Length Mean,0.922285,0.922285
77,Bwd Packet Length Mean,Packet Length Std,0.920495,0.920495
78,Packet Length Std,Bwd Segment Size Avg,0.920495,0.920495
79,Fwd IAT Std,Fwd IAT Max,0.918383,0.918383
80,Packet Length Max,Packet Length Mean,0.918208,0.918208
81,Average Packet Size,Bwd Segment Size Avg,0.916169,0.916169
82,Bwd Packet Length Mean,Average Packet Size,0.916169,0.916169
83,Flow IAT Max,Fwd IAT Std,0.916169,0.916169
84,Fwd IAT Std,Idle Max,0.915432,0.915432
85,Packet Length Max,Average Packet Size,0.912881,0.912881
86,Flow IAT Std,Idle Min,0.909045,0.909045
87,Bwd Packet Length Mean,Packet Length Max,0.905494,0.905494
88,Packet Length Max,Bwd Segment Size Avg,0.905494,0.905494
89,Fwd IAT Std,Idle Mean,0.904435,0.904435
90,Active Mean,Active Min,0.903426,0.903426
91,Flow IAT Mean,Fwd IAT Mean,0.900435,0.900435
92,Packet Length Max,Packet Length Variance,0.896057,0.896057
93,Fwd Packet Length Std,Fwd Segment Size Avg,0.894272,0.894272
94,Fwd Packet Length Mean,Fwd Packet Length Std,0.894272,0.894272
95,Bwd Packet Length Std,Packet Length Variance,0.891430,0.891430
96,Fwd Packet Length Max,Fwd Packet Length Mean,0.888242,0.888242
97,Fwd Packet Length Max,Fwd Segment Size Avg,0.888242,0.888242
98,Fwd IAT Mean,Fwd IAT Min,0.885596,0.885596
99,Bwd Packet Length Max,Packet Length Mean,0.881271,0.881271
100,Fwd IAT Min,Bwd IAT Min,0.880681,0.880681

Pearson was calculated for all 2,415 unique pairs among the 70 included training features, while the output shows the 100 strongest pairs. The strongest relationships mainly form recurring clusters:

- forward/backward packet and byte totals, subflow values, header lengths and active-data counts;
- packet-length means, segment-size averages and other packet-length summaries;
- flow duration, inter-arrival-time maxima and idle-period statistics.

Several differently defined flag counters are also almost or exactly correlated in this dataset, including `Fwd PSH Flags` with `SYN Flag Count`, `Fwd URG Flags` with `CWR Flag Count`, and `RST Flag Count` with `ECE Flag Count`. This is evidence about their behavior in CIC-IDS-2017, not evidence that the features have the same meaning. Therefore no feature is removed from this table alone; the correlated clusters must be combined with feature meaning and target relevance before choosing what to retain.

## 11. Calculate Spearman feature correlations

Calculate Spearman rank correlations using the same 70 training features as Pearson. Spearman detects strong monotonic relationships even when their shape is nonlinear. Calculate every unique pair, but display only the top 100 without selecting or removing features.

In [11]:
spearman_correlation_matrix = X_train[
    correlation_feature_columns
].corr(method="spearman")

spearman_correlation_pairs = pd.DataFrame(
    (
        (
            first_feature,
            second_feature,
            spearman_correlation_matrix.at[
                first_feature, second_feature
            ],
        )
        for first_feature, second_feature in combinations(
            correlation_feature_columns, 2
        )
    ),
    columns=["Feature 1", "Feature 2", "Spearman correlation"],
)
spearman_correlation_pairs["Absolute correlation"] = (
    spearman_correlation_pairs["Spearman correlation"].abs()
)
spearman_correlation_pairs.sort_values(
    "Absolute correlation", ascending=False, inplace=True
)
spearman_correlation_pairs.index = pd.RangeIndex(
    start=1,
    stop=len(spearman_correlation_pairs) + 1,
    name="Pair",
)

print(f"Training features included: {len(correlation_feature_columns)}")
print(f"Unique feature pairs checked: {len(spearman_correlation_pairs):,}")
print(f"Top {TOP_CORRELATION_PAIRS_TO_DISPLAY} pairs are displayed below.")

spearman_correlation_display = spearman_correlation_pairs.head(
    TOP_CORRELATION_PAIRS_TO_DISPLAY
).copy()
spearman_correlation_display["Spearman correlation"] = (
    spearman_correlation_display["Spearman correlation"].round(6)
)
spearman_correlation_display["Absolute correlation"] = (
    spearman_correlation_display["Absolute correlation"].round(6)
)
with pd.option_context("display.max_rows", None):
    display(spearman_correlation_display)

Training features included: 70
Unique feature pairs checked: 2,415
Top 100 pairs are displayed below.

,Feature 1,Feature 2,Spearman correlation,Absolute correlation
Pair,,,,
1,Total Length of Bwd Packet,Subflow Bwd Bytes,1.000000,1.000000
2,Fwd URG Flags,CWR Flag Count,1.000000,1.000000
3,Total Fwd Packet,Subflow Fwd Packets,1.000000,1.000000
4,Total Bwd packets,Subflow Bwd Packets,1.000000,1.000000
5,Total Length of Fwd Packet,Subflow Fwd Bytes,1.000000,1.000000
6,Fwd PSH Flags,SYN Flag Count,1.000000,1.000000
7,Bwd Packet Length Mean,Bwd Segment Size Avg,1.000000,1.000000
8,Fwd Packet Length Mean,Fwd Segment Size Avg,1.000000,1.000000
9,Packet Length Std,Packet Length Variance,0.999984,0.999984
10,Idle Mean,Idle Max,0.999575,0.999575
11,Active Mean,Active Max,0.999435,0.999435
12,Idle Mean,Idle Min,0.999172,0.999172
13,Bwd IAT Mean,Bwd IAT Max,0.998577,0.998577
14,Idle Max,Idle Min,0.998159,0.998159
15,Active Mean,Active Min,0.998134,0.998134
16,RST Flag Count,ECE Flag Count,0.998115,0.998115
17,Bwd IAT Total,Bwd IAT Max,0.998108,0.998108
18,Bwd IAT Total,Bwd IAT Mean,0.997204,0.997204
19,Active Max,Active Min,0.996717,0.996717
20,Fwd IAT Mean,Fwd IAT Max,0.996716,0.996716
21,Flow Packets/s,Flow IAT Mean,-0.996700,0.996700
22,Flow Packets/s,Fwd Packets/s,0.996531,0.996531
23,Packet Length Mean,Average Packet Size,0.996278,0.996278
24,Fwd IAT Total,Fwd IAT Max,0.995388,0.995388
25,Fwd IAT Total,Fwd IAT Mean,0.992451,0.992451
26,Flow IAT Mean,Fwd Packets/s,-0.992251,0.992251
27,Flow Duration,Flow IAT Max,0.991306,0.991306
28,Flow Packets/s,Flow IAT Max,-0.989351,0.989351
29,Flow IAT Max,Fwd Packets/s,-0.988734,0.988734
30,Fwd Packet Length Min,Packet Length Min,0.987098,0.987098
31,Total Length of Bwd Packet,Bwd Packet Length Max,0.983454,0.983454
32,Bwd Packet Length Max,Subflow Bwd Bytes,0.983454,0.983454
33,Bwd Packet Length Max,Bwd Segment Size Avg,0.983023,0.983023
34,Bwd Packet Length Max,Bwd Packet Length Mean,0.983023,0.983023
35,Packet Length Max,Packet Length Mean,0.982925,0.982925
36,Flow Duration,Flow Packets/s,-0.980667,0.980667
37,Flow Duration,Fwd Packets/s,-0.980512,0.980512
38,Flow IAT Mean,Flow IAT Max,0.979830,0.979830
39,Total Bwd packets,Bwd Header Length,0.977542,0.977542
40,Bwd Header Length,Subflow Bwd Packets,0.977542,0.977542
41,Packet Length Max,Average Packet Size,0.973878,0.973878
42,Packet Length Max,Packet Length Variance,0.973054,0.973054
43,Packet Length Max,Packet Length Std,0.973036,0.973036
44,Bwd Segment Size Avg,Subflow Bwd Bytes,0.970771,0.970771
45,Total Length of Bwd Packet,Bwd Segment Size Avg,0.970771,0.970771
46,Bwd Packet Length Mean,Subflow Bwd Bytes,0.970771,0.970771
47,Total Length of Bwd Packet,Bwd Packet Length Mean,0.970771,0.970771
48,Flow Duration,Flow IAT Mean,0.969018,0.969018
49,Active Min,Idle Min,0.966753,0.966753
50,Active Min,Idle Mean,0.966170,0.966170
51,Active Mean,Idle Min,0.966006,0.966006
52,Active Mean,Idle Mean,0.965872,0.965872
53,Active Max,Idle Max,0.965779,0.965779
54,Active Mean,Idle Max,0.965757,0.965757
55,Active Min,Idle Max,0.965748,0.965748
56,Active Max,Idle Mean,0.965712,0.965712
57,Active Max,Idle Min,0.965660,0.965660
58,Fwd Packet Length Max,Fwd Packet Length Mean,0.946426,0.946426
59,Fwd Packet Length Max,Fwd Segment Size Avg,0.946426,0.946426
60,Total Fwd Packet,Fwd Header Length,0.944705,0.944705
61,Fwd Header Length,Subflow Fwd Packets,0.944705,0.944705
62,Fwd Packet Length Max,Subflow Fwd Bytes,0.943870,0.943870
63,Total Length of Fwd Packet,Fwd Packet Length Max,0.943870,0.943870
64,Packet Length Mean,Packet Length Variance,0.942539,0.942539
65,Packet Length Mean,Packet Length Std,0.942522,0.942522
66,Bwd Packet Length Max,Packet Length Max,0.940042,0.940042
67,Bwd IAT Total,Subflow Bwd Packets,0.933995,0.933995
68,Total Bwd packets,Bwd IAT Total,0.933995,0.933995
69,Active Std,Idle Std,0.932143,0.932143
70,Packet Length Variance,Average Packet Size,0.931705,0.931705
71,Packet Length Std,Average Packet Size,0.931690,0.931690
72,Bwd IAT Max,Subflow Bwd Packets,0.927204,0.927204
73,Total Bwd packets,Bwd IAT Max,0.927204,0.927204
74,Total Length of Bwd Packet,Packet Length Max,0.924160,0.924160
75,Packet Length Max,Subflow Bwd Bytes,0.924160,0.924160
76,Bwd Packet Length Max,Packet Length Variance,0.922396,0.922396
77,Bwd Packet Length Max,Packet Length Std,0.922377,0.922377
78,Bwd Packet Length Max,Packet Length Mean,0.921516,0.921516
79,Total Bwd packets,Bwd IAT Mean,0.921182,0.921182
80,Bwd IAT Mean,Subflow Bwd Packets,0.921182,0.921182
81,Packet Length Mean,Bwd Segment Size Avg,0.920806,0.920806
82,Bwd Packet Length Mean,Packet Length Mean,0.920806,0.920806
83,Fwd IAT Total,Subflow Fwd Packets,0.919386,0.919386
84,Total Fwd Packet,Fwd IAT Total,0.919386,0.919386
85,Average Packet Size,Bwd Segment Size Avg,0.918555,0.918555
86,Bwd Packet Length Mean,Average Packet Size,0.918555,0.918555
87,Packet Length Max,Bwd Segment Size Avg,0.917347,0.917347
88,Bwd Packet Length Mean,Packet Length Max,0.917347,0.917347
89,Bwd Packet Length Max,Average Packet Size,0.912982,0.912982
90,Bwd IAT Total,Bwd Header Length,0.912376,0.912376
91,Total Length of Bwd Packet,Packet Length Mean,0.908264,0.908264
92,Packet Length Mean,Subflow Bwd Bytes,0.908264,0.908264
93,Total Length of Bwd Packet,Packet Length Variance,0.907750,0.907750
94,Packet Length Variance,Subflow Bwd Bytes,0.907750,0.907750
95,Total Length of Bwd Packet,Packet Length Std,0.907734,0.907734
96,Packet Length Std,Subflow Bwd Bytes,0.907734,0.907734
97,Bwd IAT Max,Bwd Header Length,0.906030,0.906030
98,Total Fwd Packet,Fwd IAT Max,0.904278,0.904278
99,Fwd IAT Max,Subflow Fwd Packets,0.904278,0.904278
100,Packet Length Variance,Bwd Segment Size Avg,0.901422,0.901422

Spearman exposes strong monotonic relationships that Pearson does not capture well. Notable examples include `Packet Length Std` with `Packet Length Variance` (Pearson `0.925`, Spearman `1.000`), `Active Mean` with `Active Max` (Pearson `0.830`, Spearman `0.999`), and `Flow Packets/s` with `Flow IAT Mean` (Pearson `-0.080`, Spearman `-0.997`). The exact total/subflow and directional mean/segment-size relationships remain at or near one under both methods. This demonstrates that Pearson alone is insufficient for the redundancy audit, but a high Spearman value still identifies a candidate relationship rather than authorizing deletion.

## 12. Combine MI, Pearson and Spearman results

Join the two complete correlation results with the feature-to-label MI scores. Sort all pairs by the larger of their absolute Pearson and Spearman correlations, but display only the top 100. No filtering rule is applied.

In [12]:
mi_score_by_feature = mutual_information_ranking.set_index(
    "Feature"
)["Mutual information"]

combined_filter_results = (
    pearson_correlation_pairs[
        ["Feature 1", "Feature 2", "Pearson correlation"]
    ]
    .merge(
        spearman_correlation_pairs[
            ["Feature 1", "Feature 2", "Spearman correlation"]
        ],
        on=["Feature 1", "Feature 2"],
        how="inner",
        validate="one_to_one",
    )
)
combined_filter_results.insert(
    1,
    "Feature 1 MI",
    combined_filter_results["Feature 1"].map(mi_score_by_feature),
)
combined_filter_results.insert(
    3,
    "Feature 2 MI",
    combined_filter_results["Feature 2"].map(mi_score_by_feature),
)
combined_filter_results["Absolute Pearson correlation"] = (
    combined_filter_results["Pearson correlation"].abs()
)
combined_filter_results["Absolute Spearman correlation"] = (
    combined_filter_results["Spearman correlation"].abs()
)
combined_filter_results["Maximum absolute correlation"] = (
    combined_filter_results[
        [
            "Absolute Pearson correlation",
            "Absolute Spearman correlation",
        ]
    ].max(axis=1)
)
combined_filter_results.sort_values(
    "Maximum absolute correlation",
    ascending=False,
    inplace=True,
)
combined_filter_results.index = pd.RangeIndex(
    start=1,
    stop=len(combined_filter_results) + 1,
    name="Pair",
)

print(f"Combined feature pairs: {len(combined_filter_results):,}")
print(f"Top {TOP_CORRELATION_PAIRS_TO_DISPLAY} pairs are displayed below.")

combined_filter_display = combined_filter_results.head(
    TOP_CORRELATION_PAIRS_TO_DISPLAY
).copy()
numeric_result_columns = [
    column
    for column in combined_filter_display.columns
    if column not in ["Feature 1", "Feature 2"]
]
combined_filter_display[numeric_result_columns] = (
    combined_filter_display[numeric_result_columns].round(6)
)
with pd.option_context("display.max_rows", None):
    display(combined_filter_display)

Combined feature pairs: 2,415
Top 100 pairs are displayed below.

,Feature 1,Feature 1 MI,Feature 2,Feature 2 MI,Pearson correlation,Spearman correlation,Absolute Pearson correlation,Absolute Spearman correlation,Maximum absolute correlation
Pair,,,,,,,,,
1,Bwd Packet Length Mean,0.490913,Bwd Segment Size Avg,0.490572,1.000000,1.000000,1.000000,1.000000,1.000000
2,Total Length of Bwd Packet,0.498369,Subflow Bwd Bytes,0.498750,1.000000,1.000000,1.000000,1.000000,1.000000
3,Total Length of Fwd Packet,0.485725,Subflow Fwd Bytes,0.485743,0.999999,1.000000,0.999999,1.000000,1.000000
4,Fwd Packet Length Mean,0.401005,Fwd Segment Size Avg,0.401476,1.000000,1.000000,1.000000,1.000000,1.000000
5,Total Bwd packets,0.270560,Subflow Bwd Packets,0.270831,1.000000,1.000000,1.000000,1.000000,1.000000
6,Fwd URG Flags,0.000021,CWR Flag Count,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
7,Fwd PSH Flags,0.019300,SYN Flag Count,0.018975,1.000000,1.000000,1.000000,1.000000,1.000000
8,Total Fwd Packet,0.247153,Subflow Fwd Packets,0.246821,1.000000,1.000000,1.000000,1.000000,1.000000
9,Packet Length Std,0.558339,Packet Length Variance,0.556995,0.924830,0.999984,0.924830,0.999984,0.999984
10,Idle Mean,0.199806,Idle Max,0.203883,0.990370,0.999575,0.990370,0.999575,0.999575
11,Active Mean,0.192799,Active Max,0.190989,0.830064,0.999435,0.830064,0.999435,0.999435
12,Idle Mean,0.199806,Idle Min,0.200101,0.990181,0.999172,0.990181,0.999172,0.999172
13,Bwd IAT Mean,0.247068,Bwd IAT Max,0.278824,0.708987,0.998577,0.708987,0.998577,0.998577
14,Flow Duration,0.423289,Fwd IAT Total,0.394418,0.998572,0.725214,0.998572,0.725214,0.998572
15,Idle Max,0.203883,Idle Min,0.200101,0.961706,0.998159,0.961706,0.998159,0.998159
16,Active Mean,0.192799,Active Min,0.190477,0.903426,0.998134,0.903426,0.998134,0.998134
17,Flow IAT Max,0.437281,Fwd IAT Max,0.411720,0.998115,0.701718,0.998115,0.701718,0.998115
18,RST Flag Count,0.000000,ECE Flag Count,0.000000,0.998115,0.998115,0.998115,0.998115,0.998115
19,Bwd IAT Total,0.262259,Bwd IAT Max,0.278824,0.723496,0.998108,0.723496,0.998108,0.998108
20,Packet Length Mean,0.561130,Average Packet Size,0.589162,0.997800,0.996278,0.997800,0.996278,0.997800
21,Bwd IAT Total,0.262259,Bwd IAT Mean,0.247068,0.512687,0.997204,0.512687,0.997204,0.997204
22,Active Max,0.190989,Active Min,0.190477,0.578817,0.996717,0.578817,0.996717,0.996717
23,Fwd IAT Mean,0.380183,Fwd IAT Max,0.411720,0.682789,0.996716,0.682789,0.996716,0.996716
24,Flow Packets/s,0.389709,Flow IAT Mean,0.386053,-0.080398,-0.996700,0.080398,0.996700,0.996700
25,Flow Packets/s,0.389709,Fwd Packets/s,0.397201,0.988950,0.996531,0.988950,0.996531,0.996531
26,Fwd IAT Total,0.394418,Fwd IAT Max,0.411720,0.787150,0.995388,0.787150,0.995388,0.995388
27,Bwd Header Length,0.380564,Subflow Bwd Packets,0.270831,0.994589,0.977542,0.994589,0.977542,0.994589
28,Total Bwd packets,0.270560,Bwd Header Length,0.380564,0.994589,0.977542,0.994589,0.977542,0.994589
29,Fwd IAT Total,0.394418,Fwd IAT Mean,0.380183,0.551221,0.992451,0.551221,0.992451,0.992451
30,Total Fwd Packet,0.247153,Subflow Bwd Packets,0.270831,0.992421,0.636522,0.992421,0.636522,0.992421
31,Total Bwd packets,0.270560,Subflow Fwd Packets,0.246821,0.992421,0.636522,0.992421,0.636522,0.992421
32,Subflow Fwd Packets,0.246821,Subflow Bwd Packets,0.270831,0.992421,0.636522,0.992421,0.636522,0.992421
33,Total Fwd Packet,0.247153,Total Bwd packets,0.270560,0.992421,0.636522,0.992421,0.636522,0.992421
34,Flow IAT Mean,0.386053,Fwd Packets/s,0.397201,-0.074350,-0.992251,0.074350,0.992251,0.992251
35,Flow Duration,0.423289,Flow IAT Max,0.437281,0.785138,0.991306,0.785138,0.991306,0.991306
36,Total Bwd packets,0.270560,Total Length of Bwd Packet,0.498369,0.991177,0.879052,0.991177,0.879052,0.991177
37,Total Length of Bwd Packet,0.498369,Subflow Bwd Packets,0.270831,0.991177,0.879052,0.991177,0.879052,0.991177
38,Subflow Bwd Packets,0.270831,Subflow Bwd Bytes,0.498750,0.991155,0.879052,0.991155,0.879052,0.991155
39,Total Bwd packets,0.270560,Subflow Bwd Bytes,0.498750,0.991155,0.879052,0.991155,0.879052,0.991155
40,Fwd Header Length,0.402117,Subflow Fwd Packets,0.246821,0.989888,0.944705,0.989888,0.944705,0.989888
41,Total Fwd Packet,0.247153,Fwd Header Length,0.402117,0.989888,0.944705,0.989888,0.944705,0.989888
42,Flow Packets/s,0.389709,Flow IAT Max,0.437281,-0.104736,-0.989351,0.104736,0.989351,0.989351
43,Flow IAT Max,0.437281,Idle Max,0.203883,0.989198,0.693181,0.989198,0.693181,0.989198
44,Flow IAT Max,0.437281,Fwd Packets/s,0.397201,-0.096858,-0.988734,0.096858,0.988734,0.988734
45,Fwd IAT Max,0.411720,Idle Max,0.203883,0.988388,0.676833,0.988388,0.676833,0.988388
46,Fwd Packet Length Min,0.180397,Packet Length Min,0.185119,0.441921,0.987098,0.441921,0.987098,0.987098
47,Bwd Header Length,0.380564,Subflow Fwd Packets,0.246821,0.985444,0.632147,0.985444,0.632147,0.985444
48,Total Fwd Packet,0.247153,Bwd Header Length,0.380564,0.985444,0.632147,0.985444,0.632147,0.985444
49,Packet Length Max,0.454000,Packet Length Std,0.558339,0.984600,0.973036,0.984600,0.973036,0.984600
50,Total Length of Bwd Packet,0.498369,Bwd Packet Length Max,0.457174,0.036617,0.983454,0.036617,0.983454,0.983454
51,Bwd Packet Length Max,0.457174,Subflow Bwd Bytes,0.498750,0.036589,0.983454,0.036589,0.983454,0.983454
52,Bwd Packet Length Max,0.457174,Bwd Packet Length Std,0.324803,0.983394,0.761334,0.983394,0.761334,0.983394
53,Bwd Packet Length Max,0.457174,Bwd Segment Size Avg,0.490572,0.959202,0.983023,0.959202,0.983023,0.983023
54,Bwd Packet Length Max,0.457174,Bwd Packet Length Mean,0.490913,0.959202,0.983023,0.959202,0.983023,0.983023
55,Packet Length Max,0.454000,Packet Length Mean,0.561130,0.918208,0.982925,0.918208,0.982925,0.982925
56,Total Fwd Packet,0.247153,Total Length of Bwd Packet,0.498369,0.982504,0.562792,0.982504,0.562792,0.982504
57,Total Length of Bwd Packet,0.498369,Subflow Fwd Packets,0.246821,0.982504,0.562792,0.982504,0.562792,0.982504
58,Subflow Fwd Packets,0.246821,Subflow Bwd Bytes,0.498750,0.982477,0.562792,0.982477,0.562792,0.982477
59,Total Fwd Packet,0.247153,Subflow Bwd Bytes,0.498750,0.982477,0.562792,0.982477,0.562792,0.982477
60,Fwd Header Length,0.402117,Bwd Header Length,0.380564,0.982170,0.655521,0.982170,0.655521,0.982170
61,Flow Duration,0.423289,Flow Packets/s,0.389709,-0.122515,-0.980667,0.122515,0.980667,0.980667
62,Flow Duration,0.423289,Fwd Packets/s,0.397201,-0.113299,-0.980512,0.113299,0.980512,0.980512
63,Total Length of Bwd Packet,0.498369,Bwd Header Length,0.380564,0.980384,0.856529,0.980384,0.856529,0.980384
64,Bwd Header Length,0.380564,Subflow Bwd Bytes,0.498750,0.980352,0.856529,0.980352,0.856529,0.980352
65,Flow IAT Mean,0.386053,Flow IAT Max,0.437281,0.655949,0.979830,0.655949,0.979830,0.979830
66,Flow IAT Max,0.437281,Idle Mean,0.199806,0.979695,0.692878,0.979695,0.692878,0.979695
67,Fwd Header Length,0.402117,Subflow Bwd Packets,0.270831,0.978381,0.632837,0.978381,0.632837,0.978381
68,Total Bwd packets,0.270560,Fwd Header Length,0.402117,0.978381,0.632837,0.978381,0.632837,0.978381
69,Fwd IAT Max,0.411720,Idle Mean,0.199806,0.978123,0.676457,0.978123,0.676457,0.978123
70,Subflow Bwd Bytes,0.498750,Fwd Act Data Pkts,0.172201,0.975712,0.619161,0.975712,0.619161,0.975712
71,Total Length of Bwd Packet,0.498369,Fwd Act Data Pkts,0.172201,0.975698,0.619161,0.975698,0.619161,0.975698
72,Packet Length Max,0.454000,Average Packet Size,0.589162,0.912881,0.973878,0.912881,0.973878,0.973878
73,Packet Length Max,0.454000,Packet Length Variance,0.556995,0.896057,0.973054,0.896057,0.973054,0.973054
74,Total Bwd packets,0.270560,Fwd Act Data Pkts,0.172201,0.972013,0.679678,0.972013,0.679678,0.972013
75,Subflow Bwd Packets,0.270831,Fwd Act Data Pkts,0.172201,0.972013,0.679678,0.972013,0.679678,0.972013
76,Total Fwd Packet,0.247153,Fwd Act Data Pkts,0.172201,0.970807,0.878998,0.970807,0.878998,0.970807
77,Subflow Fwd Packets,0.246821,Fwd Act Data Pkts,0.172201,0.970807,0.878998,0.970807,0.878998,0.970807
78,Bwd Segment Size Avg,0.490572,Subflow Bwd Bytes,0.498750,0.042041,0.970771,0.042041,0.970771,0.970771
79,Total Length of Bwd Packet,0.498369,Bwd Segment Size Avg,0.490572,0.042075,0.970771,0.042075,0.970771,0.970771
80,Bwd Packet Length Mean,0.490913,Subflow Bwd Bytes,0.498750,0.042041,0.970771,0.042041,0.970771,0.970771
81,Total Length of Bwd Packet,0.498369,Bwd Packet Length Mean,0.490913,0.042075,0.970771,0.042075,0.970771,0.970771
82,Flow Duration,0.423289,Flow IAT Mean,0.386053,0.537458,0.969018,0.537458,0.969018,0.969018
83,Fwd Packet Length Max,0.439713,Fwd Packet Length Std,0.316799,0.968888,0.702317,0.968888,0.702317,0.968888
84,Active Min,0.190477,Idle Min,0.200101,0.113589,0.966753,0.113589,0.966753,0.966753
85,Active Min,0.190477,Idle Mean,0.199806,0.118953,0.966170,0.118953,0.966170,0.966170
86,Active Mean,0.192799,Idle Min,0.200101,0.110308,0.966006,0.110308,0.966006,0.966006
87,Active Mean,0.192799,Idle Mean,0.199806,0.120727,0.965872,0.120727,0.965872,0.965872
88,Active Max,0.190989,Idle Max,0.203883,0.102727,0.965779,0.102727,0.965779,0.965779
89,Active Mean,0.192799,Idle Max,0.203883,0.133444,0.965757,0.133444,0.965757,0.965757
90,Active Min,0.190477,Idle Max,0.203883,0.123596,0.965748,0.123596,0.965748,0.965748
91,Active Max,0.190989,Idle Mean,0.199806,0.088732,0.965712,0.088732,0.965712,0.965712
92,Active Max,0.190989,Idle Min,0.200101,0.077050,0.965660,0.077050,0.965660,0.965660
93,Total Length of Bwd Packet,0.498369,Fwd Header Length,0.402117,0.960740,0.560215,0.960740,0.560215,0.960740
94,Fwd Header Length,0.402117,Subflow Bwd Bytes,0.498750,0.960690,0.560215,0.960690,0.560215,0.960690
95,Flow IAT Max,0.437281,Idle Min,0.200101,0.951390,0.691830,0.951390,0.691830,0.951390
96,Bwd Header Length,0.380564,Fwd Act Data Pkts,0.172201,0.951040,0.658730,0.951040,0.658730,0.951040
97,Fwd IAT Max,0.411720,Idle Min,0.200101,0.949036,0.674756,0.949036,0.674756,0.949036
98,Bwd Packet Length Max,0.457174,Packet Length Max,0.454000,0.948345,0.940042,0.948345,0.940042,0.948345
99,Fwd Packet Length Max,0.439713,Fwd Packet Length Mean,0.401005,0.888242,0.946426,0.888242,0.946426,0.946426
100,Fwd Packet Length Max,0.439713,Fwd Segment Size Avg,0.401476,0.888242,0.946426,0.888242,0.946426,0.946426

The combined calculation contains all 2,415 pairs, while the output shows the 100 strongest according to the larger absolute Pearson or Spearman value. It shows where a future choice may be straightforward—for example, the standard-deviation and variance features are almost perfectly rank-correlated and have nearly equal MI—and where MI alone cannot decide, such as flag pairs whose scores are both approximately zero. No columns are removed here. The next stage must define candidate rules and compare the resulting feature sets through training-only model validation.

## 13. Propose correlation-based feature removals

Create a candidate feature set without modifying either split. A pair is considered highly associated when its absolute Pearson or Spearman correlation is at least `0.99`. Process features from highest to lowest MI: retain a feature unless it is highly associated with a feature already retained. When a conflict exists, record the higher-MI retained feature as the proposed alternative. This greedy procedure handles overlapping pairs without independently deleting one feature for every table row.

In [13]:
HIGH_CORRELATION_THRESHOLD = 0.99

high_correlation_relationships = combined_filter_results.loc[
    (
        combined_filter_results["Absolute Pearson correlation"]
        >= HIGH_CORRELATION_THRESHOLD
    )
    | (
        combined_filter_results["Absolute Spearman correlation"]
        >= HIGH_CORRELATION_THRESHOLD
    )
].copy()

correlation_connections = {}
for _, relationship in high_correlation_relationships.iterrows():
    first_feature = relationship["Feature 1"]
    second_feature = relationship["Feature 2"]
    correlation_connections.setdefault(first_feature, []).append(
        (second_feature, relationship)
    )
    correlation_connections.setdefault(second_feature, []).append(
        (first_feature, relationship)
    )

mi_score_by_feature = mutual_information_ranking.set_index(
    "Feature"
)["Mutual information"]
mi_ranked_features = mutual_information_ranking["Feature"].tolist()
proposed_retained_features = []
proposed_retained_feature_set = set()
removal_candidate_records = []

for feature in mi_ranked_features:
    retained_conflicts = [
        (other_feature, relationship)
        for other_feature, relationship
        in correlation_connections.get(feature, [])
        if other_feature in proposed_retained_feature_set
    ]

    if not retained_conflicts:
        proposed_retained_features.append(feature)
        proposed_retained_feature_set.add(feature)
        continue

    retained_feature, strongest_relationship = max(
        retained_conflicts,
        key=lambda item: item[1]["Maximum absolute correlation"],
    )
    removal_candidate_records.append(
        {
            "Removal candidate": feature,
            "Candidate MI": mi_score_by_feature[feature],
            "Proposed retained feature": retained_feature,
            "Retained MI": mi_score_by_feature[retained_feature],
            "MI advantage of retained feature": (
                mi_score_by_feature[retained_feature]
                - mi_score_by_feature[feature]
            ),
            "Pearson correlation": strongest_relationship[
                "Pearson correlation"
            ],
            "Spearman correlation": strongest_relationship[
                "Spearman correlation"
            ],
            "Maximum absolute correlation": strongest_relationship[
                "Maximum absolute correlation"
            ],
            "Correlated retained feature count": len(
                retained_conflicts
            ),
        }
    )

proposed_removal_candidates = pd.DataFrame(removal_candidate_records)
proposed_removal_candidates.sort_values(
    ["Maximum absolute correlation", "Candidate MI"],
    ascending=[False, False],
    inplace=True,
)
proposed_removal_candidates.index = pd.RangeIndex(
    start=1,
    stop=len(proposed_removal_candidates) + 1,
    name="Candidate",
)

proposed_retained_feature_table = mutual_information_ranking.loc[
    mutual_information_ranking["Feature"].isin(
        proposed_retained_feature_set
    )
].copy()

print(f"High-correlation relationships: {len(high_correlation_relationships)}")
print(f"Original features: {X_train.shape[1]}")
print(f"Proposed retained features: {len(proposed_retained_features)}")
print(f"Proposed removal candidates: {len(proposed_removal_candidates)}")
print("X_train and X_test remain unchanged.")

print("Proposed removal candidates:")
with pd.option_context("display.max_rows", None):
    display(proposed_removal_candidates.round(6))

print("Proposed retained features, ordered by MI rank:")
with pd.option_context("display.max_rows", None):
    display(proposed_retained_feature_table.round(6))

High-correlation relationships: 39
Original features: 71
Proposed retained features: 48
Proposed removal candidates: 23
X_train and X_test remain unchanged.
Proposed removal candidates:

,Removal candidate,Candidate MI,Proposed retained feature,Retained MI,MI advantage of retained feature,Pearson correlation,Spearman correlation,Maximum absolute correlation,Correlated retained feature count
Candidate,,,,,,,,,
1,Bwd Segment Size Avg,0.490572,Bwd Packet Length Mean,0.490913,0.000341,1.000000,1.000000,1.000000,1
2,Total Length of Bwd Packet,0.498369,Subflow Bwd Bytes,0.498750,0.000380,1.000000,1.000000,1.000000,1
3,Total Length of Fwd Packet,0.485725,Subflow Fwd Bytes,0.485743,0.000018,0.999999,1.000000,1.000000,1
4,Fwd Packet Length Mean,0.401005,Fwd Segment Size Avg,0.401476,0.000470,1.000000,1.000000,1.000000,1
5,Subflow Fwd Packets,0.246821,Total Fwd Packet,0.247153,0.000332,1.000000,1.000000,1.000000,1
6,SYN Flag Count,0.018975,Fwd PSH Flags,0.019300,0.000326,1.000000,1.000000,1.000000,1
7,CWR Flag Count,0.000000,Fwd URG Flags,0.000021,0.000021,1.000000,1.000000,1.000000,1
8,Packet Length Variance,0.556995,Packet Length Std,0.558339,0.001344,0.924830,0.999984,0.999984,1
9,Idle Mean,0.199806,Idle Max,0.203883,0.004077,0.990370,0.999575,0.999575,1
10,Active Max,0.190989,Active Mean,0.192799,0.001810,0.830064,0.999435,0.999435,1
11,Bwd IAT Mean,0.247068,Bwd IAT Max,0.278824,0.031756,0.708987,0.998577,0.998577,1
12,Idle Min,0.200101,Idle Max,0.203883,0.003782,0.961706,0.998159,0.998159,1
13,Active Min,0.190477,Active Mean,0.192799,0.002322,0.903426,0.998134,0.998134,1
14,Fwd IAT Max,0.411720,Flow IAT Max,0.437281,0.025562,0.998115,0.701718,0.998115,1
15,ECE Flag Count,0.000000,RST Flag Count,0.000000,0.000000,0.998115,0.998115,0.998115,1
16,Bwd IAT Total,0.262259,Bwd IAT Max,0.278824,0.016565,0.723496,0.998108,0.998108,1
17,Packet Length Mean,0.561130,Average Packet Size,0.589162,0.028032,0.997800,0.996278,0.997800,1
18,Flow Packets/s,0.389709,Fwd Packets/s,0.397201,0.007492,0.988950,0.996531,0.996531,1
19,Subflow Bwd Packets,0.270831,Bwd Header Length,0.380564,0.109733,0.994589,0.977542,0.994589,2
20,Total Bwd packets,0.270560,Bwd Header Length,0.380564,0.110004,0.994589,0.977542,0.994589,2
21,Fwd IAT Mean,0.380183,Fwd IAT Total,0.394418,0.014235,0.551221,0.992451,0.992451,1
22,Flow IAT Mean,0.386053,Fwd Packets/s,0.397201,0.011148,-0.074350,-0.992251,0.992251,1
23,Flow Duration,0.423289,Flow IAT Max,0.437281,0.013992,0.785138,0.991306,0.991306,1

Proposed retained features, ordered by MI rank:

                     Feature  Mutual information MI estimator input type
Rank
1        Average Packet Size            0.589162              Continuous
3          Packet Length Std            0.558339              Continuous
5          Subflow Bwd Bytes            0.498750              Continuous
7         FWD Init Win Bytes            0.497415              Continuous
8     Bwd Packet Length Mean            0.490913              Continuous
10         Subflow Fwd Bytes            0.485743              Continuous
12     Bwd Packet Length Max            0.457174              Continuous
13         Packet Length Max            0.454000              Continuous
14        Bwd Init Win Bytes            0.448389              Continuous
15     Fwd Packet Length Max            0.439713              Continuous
16              Flow IAT Max            0.437281              Continuous
17                  Dst Port            0.436298              Continuous
18              Flow Bytes/s            0.425054              Continuous
21         Fwd Header Length            0.402117              Continuous
22      Fwd Segment Size Avg            0.401476              Continuous
24             Fwd Packets/s            0.397201              Continuous
25             Fwd IAT Total            0.394418              Continuous
28             Bwd Packets/s            0.384638              Continuous
29         Bwd Header Length            0.380564              Continuous
31          Fwd Seg Size Min            0.348652              Continuous
32     Bwd Packet Length Std            0.324803              Continuous
33     Fwd Packet Length Std            0.316799              Continuous
34              Flow IAT Std            0.315470              Continuous
35               Fwd IAT Std            0.293843              Continuous
36               Bwd IAT Max            0.278824              Continuous
40                  Src Port            0.261874              Continuous
41          Total Fwd Packet            0.247153              Continuous
44     Bwd Packet Length Min            0.226311              Continuous
45             Down/Up Ratio            0.214031              Continuous
46                  Idle Max            0.203883              Continuous
49               Fwd IAT Min            0.196227              Continuous
50               Bwd IAT Std            0.194450              Continuous
51               Active Mean            0.192799              Continuous
54               Bwd IAT Min            0.186434              Continuous
55         Packet Length Min            0.185119              Continuous
56     Fwd Packet Length Min            0.180397              Continuous
57         Fwd Act Data Pkts            0.172201              Continuous
58              Flow IAT Min            0.171627              Continuous
59            PSH Flag Count            0.152155              Continuous
60            ACK Flag Count            0.121559              Continuous
61                  Protocol            0.099079                Discrete
62                  Idle Std            0.038311              Continuous
63            FIN Flag Count            0.035941              Continuous
64            URG Flag Count            0.034707              Continuous
65                Active Std            0.020691              Continuous
66             Fwd PSH Flags            0.019300              Continuous
68             Fwd URG Flags            0.000021              Continuous
70            RST Flag Count            0.000000              Continuous

The `0.99` rule finds 39 high-correlation relationships. The MI-ordered greedy procedure proposes retaining 48 of the 71 features and marks 23 as removal candidates, while leaving both data splits unchanged. Some proposals describe direct or near-direct redundancy, including directional packet-length means versus segment-size averages, total versus subflow measurements, and packet-length standard deviation versus variance.

The table is not yet a safe deletion list. Several exact pairs have negligible MI differences, so estimator noise or feature clarity may be more important than which score is microscopically larger. The flag pairs have different meanings despite matching behavior in this dataset. Other proposals are driven mainly by Spearman—for example, `Flow IAT Mean` versus `Fwd Packets/s` and `Flow Duration` versus `Flow IAT Max`—and identify monotonic association rather than interchangeable measurements. Likewise, packet-count features should not be discarded solely because they correlate with header length. These cases require review before creating the reduced feature set, and the eventual proposal must be compared with all 71 features through training-only validation.